# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/code/Github_repo/compiler-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/code/Github_repo/compiler-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/code/Github_repo/compiler-main/CMakeFiles /home/code/Github_repo/compiler-main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/code/Github_repo/compiler-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compiler

# Build rule for target.
compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compiler
.PHONY : compiler

# fast build rule for target.
compiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/build
.PHONY : compiler/fast

src/back_end/arm.o: src/back_end/arm.cpp.o
.PHONY : src/back_end/arm.o

# target to build an object file
src/back_end/arm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/back_end/arm.cpp.o
.PHONY : src/back_end/arm.cpp.o

src/back_end/arm.i: src/back_end/arm.cpp.i
.PHONY : src/back_end/arm.i

# target to preprocess a source file
src/back_end/arm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/back_end/arm.cpp.i
.PHONY : src/back_end/arm.cpp.i

src/back_end/arm.s: src/back_end/arm.cpp.s
.PHONY : src/back_end/arm.s

# target to generate assembly for a file
src/back_end/arm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/back_end/arm.cpp.s
.PHONY : src/back_end/arm.cpp.s

src/back_end/arm_struct.o: src/back_end/arm_struct.cpp.o
.PHONY : src/back_end/arm_struct.o

# target to build an object file
src/back_end/arm_struct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/back_end/arm_struct.cpp.o
.PHONY : src/back_end/arm_struct.cpp.o

src/back_end/arm_struct.i: src/back_end/arm_struct.cpp.i
.PHONY : src/back_end/arm_struct.i

# target to preprocess a source file
src/back_end/arm_struct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/back_end/arm_struct.cpp.i
.PHONY : src/back_end/arm_struct.cpp.i

src/back_end/arm_struct.s: src/back_end/arm_struct.cpp.s
.PHONY : src/back_end/arm_struct.s

# target to generate assembly for a file
src/back_end/arm_struct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/back_end/arm_struct.cpp.s
.PHONY : src/back_end/arm_struct.cpp.s

src/evaluate.o: src/evaluate.cpp.o
.PHONY : src/evaluate.o

# target to build an object file
src/evaluate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/evaluate.cpp.o
.PHONY : src/evaluate.cpp.o

src/evaluate.i: src/evaluate.cpp.i
.PHONY : src/evaluate.i

# target to preprocess a source file
src/evaluate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/evaluate.cpp.i
.PHONY : src/evaluate.cpp.i

src/evaluate.s: src/evaluate.cpp.s
.PHONY : src/evaluate.s

# target to generate assembly for a file
src/evaluate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/evaluate.cpp.s
.PHONY : src/evaluate.cpp.s

src/front_end/ast.o: src/front_end/ast.cpp.o
.PHONY : src/front_end/ast.o

# target to build an object file
src/front_end/ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/front_end/ast.cpp.o
.PHONY : src/front_end/ast.cpp.o

src/front_end/ast.i: src/front_end/ast.cpp.i
.PHONY : src/front_end/ast.i

# target to preprocess a source file
src/front_end/ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/front_end/ast.cpp.i
.PHONY : src/front_end/ast.cpp.i

src/front_end/ast.s: src/front_end/ast.cpp.s
.PHONY : src/front_end/ast.s

# target to generate assembly for a file
src/front_end/ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/front_end/ast.cpp.s
.PHONY : src/front_end/ast.cpp.s

src/front_end/parser.o: src/front_end/parser.cpp.o
.PHONY : src/front_end/parser.o

# target to build an object file
src/front_end/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/front_end/parser.cpp.o
.PHONY : src/front_end/parser.cpp.o

src/front_end/parser.i: src/front_end/parser.cpp.i
.PHONY : src/front_end/parser.i

# target to preprocess a source file
src/front_end/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/front_end/parser.cpp.i
.PHONY : src/front_end/parser.cpp.i

src/front_end/parser.s: src/front_end/parser.cpp.s
.PHONY : src/front_end/parser.s

# target to generate assembly for a file
src/front_end/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/front_end/parser.cpp.s
.PHONY : src/front_end/parser.cpp.s

src/front_end/scanner.o: src/front_end/scanner.cpp.o
.PHONY : src/front_end/scanner.o

# target to build an object file
src/front_end/scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/front_end/scanner.cpp.o
.PHONY : src/front_end/scanner.cpp.o

src/front_end/scanner.i: src/front_end/scanner.cpp.i
.PHONY : src/front_end/scanner.i

# target to preprocess a source file
src/front_end/scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/front_end/scanner.cpp.i
.PHONY : src/front_end/scanner.cpp.i

src/front_end/scanner.s: src/front_end/scanner.cpp.s
.PHONY : src/front_end/scanner.s

# target to generate assembly for a file
src/front_end/scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/front_end/scanner.cpp.s
.PHONY : src/front_end/scanner.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/middle_end/construct_ir_module.o: src/middle_end/construct_ir_module.cpp.o
.PHONY : src/middle_end/construct_ir_module.o

# target to build an object file
src/middle_end/construct_ir_module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/construct_ir_module.cpp.o
.PHONY : src/middle_end/construct_ir_module.cpp.o

src/middle_end/construct_ir_module.i: src/middle_end/construct_ir_module.cpp.i
.PHONY : src/middle_end/construct_ir_module.i

# target to preprocess a source file
src/middle_end/construct_ir_module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/construct_ir_module.cpp.i
.PHONY : src/middle_end/construct_ir_module.cpp.i

src/middle_end/construct_ir_module.s: src/middle_end/construct_ir_module.cpp.s
.PHONY : src/middle_end/construct_ir_module.s

# target to generate assembly for a file
src/middle_end/construct_ir_module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/construct_ir_module.cpp.s
.PHONY : src/middle_end/construct_ir_module.cpp.s

src/middle_end/generate_ir.o: src/middle_end/generate_ir.cpp.o
.PHONY : src/middle_end/generate_ir.o

# target to build an object file
src/middle_end/generate_ir.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/generate_ir.cpp.o
.PHONY : src/middle_end/generate_ir.cpp.o

src/middle_end/generate_ir.i: src/middle_end/generate_ir.cpp.i
.PHONY : src/middle_end/generate_ir.i

# target to preprocess a source file
src/middle_end/generate_ir.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/generate_ir.cpp.i
.PHONY : src/middle_end/generate_ir.cpp.i

src/middle_end/generate_ir.s: src/middle_end/generate_ir.cpp.s
.PHONY : src/middle_end/generate_ir.s

# target to generate assembly for a file
src/middle_end/generate_ir.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/generate_ir.cpp.s
.PHONY : src/middle_end/generate_ir.cpp.s

src/middle_end/ir.o: src/middle_end/ir.cpp.o
.PHONY : src/middle_end/ir.o

# target to build an object file
src/middle_end/ir.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ir.cpp.o
.PHONY : src/middle_end/ir.cpp.o

src/middle_end/ir.i: src/middle_end/ir.cpp.i
.PHONY : src/middle_end/ir.i

# target to preprocess a source file
src/middle_end/ir.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ir.cpp.i
.PHONY : src/middle_end/ir.cpp.i

src/middle_end/ir.s: src/middle_end/ir.cpp.s
.PHONY : src/middle_end/ir.s

# target to generate assembly for a file
src/middle_end/ir.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ir.cpp.s
.PHONY : src/middle_end/ir.cpp.s

src/middle_end/ir_struct.o: src/middle_end/ir_struct.cpp.o
.PHONY : src/middle_end/ir_struct.o

# target to build an object file
src/middle_end/ir_struct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ir_struct.cpp.o
.PHONY : src/middle_end/ir_struct.cpp.o

src/middle_end/ir_struct.i: src/middle_end/ir_struct.cpp.i
.PHONY : src/middle_end/ir_struct.i

# target to preprocess a source file
src/middle_end/ir_struct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ir_struct.cpp.i
.PHONY : src/middle_end/ir_struct.cpp.i

src/middle_end/ir_struct.s: src/middle_end/ir_struct.cpp.s
.PHONY : src/middle_end/ir_struct.s

# target to generate assembly for a file
src/middle_end/ir_struct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ir_struct.cpp.s
.PHONY : src/middle_end/ir_struct.cpp.s

src/middle_end/ssa.o: src/middle_end/ssa.cpp.o
.PHONY : src/middle_end/ssa.o

# target to build an object file
src/middle_end/ssa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ssa.cpp.o
.PHONY : src/middle_end/ssa.cpp.o

src/middle_end/ssa.i: src/middle_end/ssa.cpp.i
.PHONY : src/middle_end/ssa.i

# target to preprocess a source file
src/middle_end/ssa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ssa.cpp.i
.PHONY : src/middle_end/ssa.cpp.i

src/middle_end/ssa.s: src/middle_end/ssa.cpp.s
.PHONY : src/middle_end/ssa.s

# target to generate assembly for a file
src/middle_end/ssa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ssa.cpp.s
.PHONY : src/middle_end/ssa.cpp.s

src/middle_end/ssa_struct.o: src/middle_end/ssa_struct.cpp.o
.PHONY : src/middle_end/ssa_struct.o

# target to build an object file
src/middle_end/ssa_struct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ssa_struct.cpp.o
.PHONY : src/middle_end/ssa_struct.cpp.o

src/middle_end/ssa_struct.i: src/middle_end/ssa_struct.cpp.i
.PHONY : src/middle_end/ssa_struct.i

# target to preprocess a source file
src/middle_end/ssa_struct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ssa_struct.cpp.i
.PHONY : src/middle_end/ssa_struct.cpp.i

src/middle_end/ssa_struct.s: src/middle_end/ssa_struct.cpp.s
.PHONY : src/middle_end/ssa_struct.s

# target to generate assembly for a file
src/middle_end/ssa_struct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/middle_end/ssa_struct.cpp.s
.PHONY : src/middle_end/ssa_struct.cpp.s

src/optimizer/allocate_register.o: src/optimizer/allocate_register.cpp.o
.PHONY : src/optimizer/allocate_register.o

# target to build an object file
src/optimizer/allocate_register.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/allocate_register.cpp.o
.PHONY : src/optimizer/allocate_register.cpp.o

src/optimizer/allocate_register.i: src/optimizer/allocate_register.cpp.i
.PHONY : src/optimizer/allocate_register.i

# target to preprocess a source file
src/optimizer/allocate_register.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/allocate_register.cpp.i
.PHONY : src/optimizer/allocate_register.cpp.i

src/optimizer/allocate_register.s: src/optimizer/allocate_register.cpp.s
.PHONY : src/optimizer/allocate_register.s

# target to generate assembly for a file
src/optimizer/allocate_register.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/allocate_register.cpp.s
.PHONY : src/optimizer/allocate_register.cpp.s

src/optimizer/arm_liveness_analysis.o: src/optimizer/arm_liveness_analysis.cpp.o
.PHONY : src/optimizer/arm_liveness_analysis.o

# target to build an object file
src/optimizer/arm_liveness_analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/arm_liveness_analysis.cpp.o
.PHONY : src/optimizer/arm_liveness_analysis.cpp.o

src/optimizer/arm_liveness_analysis.i: src/optimizer/arm_liveness_analysis.cpp.i
.PHONY : src/optimizer/arm_liveness_analysis.i

# target to preprocess a source file
src/optimizer/arm_liveness_analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/arm_liveness_analysis.cpp.i
.PHONY : src/optimizer/arm_liveness_analysis.cpp.i

src/optimizer/arm_liveness_analysis.s: src/optimizer/arm_liveness_analysis.cpp.s
.PHONY : src/optimizer/arm_liveness_analysis.s

# target to generate assembly for a file
src/optimizer/arm_liveness_analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/arm_liveness_analysis.cpp.s
.PHONY : src/optimizer/arm_liveness_analysis.cpp.s

src/optimizer/arm_offset_fixup.o: src/optimizer/arm_offset_fixup.cpp.o
.PHONY : src/optimizer/arm_offset_fixup.o

# target to build an object file
src/optimizer/arm_offset_fixup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/arm_offset_fixup.cpp.o
.PHONY : src/optimizer/arm_offset_fixup.cpp.o

src/optimizer/arm_offset_fixup.i: src/optimizer/arm_offset_fixup.cpp.i
.PHONY : src/optimizer/arm_offset_fixup.i

# target to preprocess a source file
src/optimizer/arm_offset_fixup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/arm_offset_fixup.cpp.i
.PHONY : src/optimizer/arm_offset_fixup.cpp.i

src/optimizer/arm_offset_fixup.s: src/optimizer/arm_offset_fixup.cpp.s
.PHONY : src/optimizer/arm_offset_fixup.s

# target to generate assembly for a file
src/optimizer/arm_offset_fixup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/arm_offset_fixup.cpp.s
.PHONY : src/optimizer/arm_offset_fixup.cpp.s

src/optimizer/cond_br_to_insts.o: src/optimizer/cond_br_to_insts.cpp.o
.PHONY : src/optimizer/cond_br_to_insts.o

# target to build an object file
src/optimizer/cond_br_to_insts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/cond_br_to_insts.cpp.o
.PHONY : src/optimizer/cond_br_to_insts.cpp.o

src/optimizer/cond_br_to_insts.i: src/optimizer/cond_br_to_insts.cpp.i
.PHONY : src/optimizer/cond_br_to_insts.i

# target to preprocess a source file
src/optimizer/cond_br_to_insts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/cond_br_to_insts.cpp.i
.PHONY : src/optimizer/cond_br_to_insts.cpp.i

src/optimizer/cond_br_to_insts.s: src/optimizer/cond_br_to_insts.cpp.s
.PHONY : src/optimizer/cond_br_to_insts.s

# target to generate assembly for a file
src/optimizer/cond_br_to_insts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/cond_br_to_insts.cpp.s
.PHONY : src/optimizer/cond_br_to_insts.cpp.s

src/optimizer/constant_propagation.o: src/optimizer/constant_propagation.cpp.o
.PHONY : src/optimizer/constant_propagation.o

# target to build an object file
src/optimizer/constant_propagation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/constant_propagation.cpp.o
.PHONY : src/optimizer/constant_propagation.cpp.o

src/optimizer/constant_propagation.i: src/optimizer/constant_propagation.cpp.i
.PHONY : src/optimizer/constant_propagation.i

# target to preprocess a source file
src/optimizer/constant_propagation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/constant_propagation.cpp.i
.PHONY : src/optimizer/constant_propagation.cpp.i

src/optimizer/constant_propagation.s: src/optimizer/constant_propagation.cpp.s
.PHONY : src/optimizer/constant_propagation.s

# target to generate assembly for a file
src/optimizer/constant_propagation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/constant_propagation.cpp.s
.PHONY : src/optimizer/constant_propagation.cpp.s

src/optimizer/convert_ssa.o: src/optimizer/convert_ssa.cpp.o
.PHONY : src/optimizer/convert_ssa.o

# target to build an object file
src/optimizer/convert_ssa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/convert_ssa.cpp.o
.PHONY : src/optimizer/convert_ssa.cpp.o

src/optimizer/convert_ssa.i: src/optimizer/convert_ssa.cpp.i
.PHONY : src/optimizer/convert_ssa.i

# target to preprocess a source file
src/optimizer/convert_ssa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/convert_ssa.cpp.i
.PHONY : src/optimizer/convert_ssa.cpp.i

src/optimizer/convert_ssa.s: src/optimizer/convert_ssa.cpp.s
.PHONY : src/optimizer/convert_ssa.s

# target to generate assembly for a file
src/optimizer/convert_ssa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/convert_ssa.cpp.s
.PHONY : src/optimizer/convert_ssa.cpp.s

src/optimizer/dead_code_eliminate.o: src/optimizer/dead_code_eliminate.cpp.o
.PHONY : src/optimizer/dead_code_eliminate.o

# target to build an object file
src/optimizer/dead_code_eliminate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/dead_code_eliminate.cpp.o
.PHONY : src/optimizer/dead_code_eliminate.cpp.o

src/optimizer/dead_code_eliminate.i: src/optimizer/dead_code_eliminate.cpp.i
.PHONY : src/optimizer/dead_code_eliminate.i

# target to preprocess a source file
src/optimizer/dead_code_eliminate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/dead_code_eliminate.cpp.i
.PHONY : src/optimizer/dead_code_eliminate.cpp.i

src/optimizer/dead_code_eliminate.s: src/optimizer/dead_code_eliminate.cpp.s
.PHONY : src/optimizer/dead_code_eliminate.s

# target to generate assembly for a file
src/optimizer/dead_code_eliminate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/dead_code_eliminate.cpp.s
.PHONY : src/optimizer/dead_code_eliminate.cpp.s

src/optimizer/dead_function_eliminate.o: src/optimizer/dead_function_eliminate.cpp.o
.PHONY : src/optimizer/dead_function_eliminate.o

# target to build an object file
src/optimizer/dead_function_eliminate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/dead_function_eliminate.cpp.o
.PHONY : src/optimizer/dead_function_eliminate.cpp.o

src/optimizer/dead_function_eliminate.i: src/optimizer/dead_function_eliminate.cpp.i
.PHONY : src/optimizer/dead_function_eliminate.i

# target to preprocess a source file
src/optimizer/dead_function_eliminate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/dead_function_eliminate.cpp.i
.PHONY : src/optimizer/dead_function_eliminate.cpp.i

src/optimizer/dead_function_eliminate.s: src/optimizer/dead_function_eliminate.cpp.s
.PHONY : src/optimizer/dead_function_eliminate.s

# target to generate assembly for a file
src/optimizer/dead_function_eliminate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/dead_function_eliminate.cpp.s
.PHONY : src/optimizer/dead_function_eliminate.cpp.s

src/optimizer/dominant.o: src/optimizer/dominant.cpp.o
.PHONY : src/optimizer/dominant.o

# target to build an object file
src/optimizer/dominant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/dominant.cpp.o
.PHONY : src/optimizer/dominant.cpp.o

src/optimizer/dominant.i: src/optimizer/dominant.cpp.i
.PHONY : src/optimizer/dominant.i

# target to preprocess a source file
src/optimizer/dominant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/dominant.cpp.i
.PHONY : src/optimizer/dominant.cpp.i

src/optimizer/dominant.s: src/optimizer/dominant.cpp.s
.PHONY : src/optimizer/dominant.s

# target to generate assembly for a file
src/optimizer/dominant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/dominant.cpp.s
.PHONY : src/optimizer/dominant.cpp.s

src/optimizer/generate_arm_from_ssa.o: src/optimizer/generate_arm_from_ssa.cpp.o
.PHONY : src/optimizer/generate_arm_from_ssa.o

# target to build an object file
src/optimizer/generate_arm_from_ssa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/generate_arm_from_ssa.cpp.o
.PHONY : src/optimizer/generate_arm_from_ssa.cpp.o

src/optimizer/generate_arm_from_ssa.i: src/optimizer/generate_arm_from_ssa.cpp.i
.PHONY : src/optimizer/generate_arm_from_ssa.i

# target to preprocess a source file
src/optimizer/generate_arm_from_ssa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/generate_arm_from_ssa.cpp.i
.PHONY : src/optimizer/generate_arm_from_ssa.cpp.i

src/optimizer/generate_arm_from_ssa.s: src/optimizer/generate_arm_from_ssa.cpp.s
.PHONY : src/optimizer/generate_arm_from_ssa.s

# target to generate assembly for a file
src/optimizer/generate_arm_from_ssa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/generate_arm_from_ssa.cpp.s
.PHONY : src/optimizer/generate_arm_from_ssa.cpp.s

src/optimizer/global_value_numbering.o: src/optimizer/global_value_numbering.cpp.o
.PHONY : src/optimizer/global_value_numbering.o

# target to build an object file
src/optimizer/global_value_numbering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/global_value_numbering.cpp.o
.PHONY : src/optimizer/global_value_numbering.cpp.o

src/optimizer/global_value_numbering.i: src/optimizer/global_value_numbering.cpp.i
.PHONY : src/optimizer/global_value_numbering.i

# target to preprocess a source file
src/optimizer/global_value_numbering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/global_value_numbering.cpp.i
.PHONY : src/optimizer/global_value_numbering.cpp.i

src/optimizer/global_value_numbering.s: src/optimizer/global_value_numbering.cpp.s
.PHONY : src/optimizer/global_value_numbering.s

# target to generate assembly for a file
src/optimizer/global_value_numbering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/global_value_numbering.cpp.s
.PHONY : src/optimizer/global_value_numbering.cpp.s

src/optimizer/instruction_combining.o: src/optimizer/instruction_combining.cpp.o
.PHONY : src/optimizer/instruction_combining.o

# target to build an object file
src/optimizer/instruction_combining.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/instruction_combining.cpp.o
.PHONY : src/optimizer/instruction_combining.cpp.o

src/optimizer/instruction_combining.i: src/optimizer/instruction_combining.cpp.i
.PHONY : src/optimizer/instruction_combining.i

# target to preprocess a source file
src/optimizer/instruction_combining.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/instruction_combining.cpp.i
.PHONY : src/optimizer/instruction_combining.cpp.i

src/optimizer/instruction_combining.s: src/optimizer/instruction_combining.cpp.s
.PHONY : src/optimizer/instruction_combining.s

# target to generate assembly for a file
src/optimizer/instruction_combining.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/instruction_combining.cpp.s
.PHONY : src/optimizer/instruction_combining.cpp.s

src/optimizer/ir_liveness_analysis.o: src/optimizer/ir_liveness_analysis.cpp.o
.PHONY : src/optimizer/ir_liveness_analysis.o

# target to build an object file
src/optimizer/ir_liveness_analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/ir_liveness_analysis.cpp.o
.PHONY : src/optimizer/ir_liveness_analysis.cpp.o

src/optimizer/ir_liveness_analysis.i: src/optimizer/ir_liveness_analysis.cpp.i
.PHONY : src/optimizer/ir_liveness_analysis.i

# target to preprocess a source file
src/optimizer/ir_liveness_analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/ir_liveness_analysis.cpp.i
.PHONY : src/optimizer/ir_liveness_analysis.cpp.i

src/optimizer/ir_liveness_analysis.s: src/optimizer/ir_liveness_analysis.cpp.s
.PHONY : src/optimizer/ir_liveness_analysis.s

# target to generate assembly for a file
src/optimizer/ir_liveness_analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/ir_liveness_analysis.cpp.s
.PHONY : src/optimizer/ir_liveness_analysis.cpp.s

src/optimizer/loop_invariant_extrapolation.o: src/optimizer/loop_invariant_extrapolation.cpp.o
.PHONY : src/optimizer/loop_invariant_extrapolation.o

# target to build an object file
src/optimizer/loop_invariant_extrapolation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/loop_invariant_extrapolation.cpp.o
.PHONY : src/optimizer/loop_invariant_extrapolation.cpp.o

src/optimizer/loop_invariant_extrapolation.i: src/optimizer/loop_invariant_extrapolation.cpp.i
.PHONY : src/optimizer/loop_invariant_extrapolation.i

# target to preprocess a source file
src/optimizer/loop_invariant_extrapolation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/loop_invariant_extrapolation.cpp.i
.PHONY : src/optimizer/loop_invariant_extrapolation.cpp.i

src/optimizer/loop_invariant_extrapolation.s: src/optimizer/loop_invariant_extrapolation.cpp.s
.PHONY : src/optimizer/loop_invariant_extrapolation.s

# target to generate assembly for a file
src/optimizer/loop_invariant_extrapolation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/loop_invariant_extrapolation.cpp.s
.PHONY : src/optimizer/loop_invariant_extrapolation.cpp.s

src/optimizer/loop_unroll.o: src/optimizer/loop_unroll.cpp.o
.PHONY : src/optimizer/loop_unroll.o

# target to build an object file
src/optimizer/loop_unroll.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/loop_unroll.cpp.o
.PHONY : src/optimizer/loop_unroll.cpp.o

src/optimizer/loop_unroll.i: src/optimizer/loop_unroll.cpp.i
.PHONY : src/optimizer/loop_unroll.i

# target to preprocess a source file
src/optimizer/loop_unroll.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/loop_unroll.cpp.i
.PHONY : src/optimizer/loop_unroll.cpp.i

src/optimizer/loop_unroll.s: src/optimizer/loop_unroll.cpp.s
.PHONY : src/optimizer/loop_unroll.s

# target to generate assembly for a file
src/optimizer/loop_unroll.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/loop_unroll.cpp.s
.PHONY : src/optimizer/loop_unroll.cpp.s

src/optimizer/reach_define.o: src/optimizer/reach_define.cpp.o
.PHONY : src/optimizer/reach_define.o

# target to build an object file
src/optimizer/reach_define.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/reach_define.cpp.o
.PHONY : src/optimizer/reach_define.cpp.o

src/optimizer/reach_define.i: src/optimizer/reach_define.cpp.i
.PHONY : src/optimizer/reach_define.i

# target to preprocess a source file
src/optimizer/reach_define.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/reach_define.cpp.i
.PHONY : src/optimizer/reach_define.cpp.i

src/optimizer/reach_define.s: src/optimizer/reach_define.cpp.s
.PHONY : src/optimizer/reach_define.s

# target to generate assembly for a file
src/optimizer/reach_define.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/reach_define.cpp.s
.PHONY : src/optimizer/reach_define.cpp.s

src/optimizer/simplify_armcode.o: src/optimizer/simplify_armcode.cpp.o
.PHONY : src/optimizer/simplify_armcode.o

# target to build an object file
src/optimizer/simplify_armcode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/simplify_armcode.cpp.o
.PHONY : src/optimizer/simplify_armcode.cpp.o

src/optimizer/simplify_armcode.i: src/optimizer/simplify_armcode.cpp.i
.PHONY : src/optimizer/simplify_armcode.i

# target to preprocess a source file
src/optimizer/simplify_armcode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/simplify_armcode.cpp.i
.PHONY : src/optimizer/simplify_armcode.cpp.i

src/optimizer/simplify_armcode.s: src/optimizer/simplify_armcode.cpp.s
.PHONY : src/optimizer/simplify_armcode.s

# target to generate assembly for a file
src/optimizer/simplify_armcode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/simplify_armcode.cpp.s
.PHONY : src/optimizer/simplify_armcode.cpp.s

src/optimizer/simplify_cfg.o: src/optimizer/simplify_cfg.cpp.o
.PHONY : src/optimizer/simplify_cfg.o

# target to build an object file
src/optimizer/simplify_cfg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/simplify_cfg.cpp.o
.PHONY : src/optimizer/simplify_cfg.cpp.o

src/optimizer/simplify_cfg.i: src/optimizer/simplify_cfg.cpp.i
.PHONY : src/optimizer/simplify_cfg.i

# target to preprocess a source file
src/optimizer/simplify_cfg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/simplify_cfg.cpp.i
.PHONY : src/optimizer/simplify_cfg.cpp.i

src/optimizer/simplify_cfg.s: src/optimizer/simplify_cfg.cpp.s
.PHONY : src/optimizer/simplify_cfg.s

# target to generate assembly for a file
src/optimizer/simplify_cfg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/simplify_cfg.cpp.s
.PHONY : src/optimizer/simplify_cfg.cpp.s

src/optimizer/ssa_simple_optimize.o: src/optimizer/ssa_simple_optimize.cpp.o
.PHONY : src/optimizer/ssa_simple_optimize.o

# target to build an object file
src/optimizer/ssa_simple_optimize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/ssa_simple_optimize.cpp.o
.PHONY : src/optimizer/ssa_simple_optimize.cpp.o

src/optimizer/ssa_simple_optimize.i: src/optimizer/ssa_simple_optimize.cpp.i
.PHONY : src/optimizer/ssa_simple_optimize.i

# target to preprocess a source file
src/optimizer/ssa_simple_optimize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/ssa_simple_optimize.cpp.i
.PHONY : src/optimizer/ssa_simple_optimize.cpp.i

src/optimizer/ssa_simple_optimize.s: src/optimizer/ssa_simple_optimize.cpp.s
.PHONY : src/optimizer/ssa_simple_optimize.s

# target to generate assembly for a file
src/optimizer/ssa_simple_optimize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compiler.dir/build.make CMakeFiles/compiler.dir/src/optimizer/ssa_simple_optimize.cpp.s
.PHONY : src/optimizer/ssa_simple_optimize.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... compiler"
	@echo "... src/back_end/arm.o"
	@echo "... src/back_end/arm.i"
	@echo "... src/back_end/arm.s"
	@echo "... src/back_end/arm_struct.o"
	@echo "... src/back_end/arm_struct.i"
	@echo "... src/back_end/arm_struct.s"
	@echo "... src/evaluate.o"
	@echo "... src/evaluate.i"
	@echo "... src/evaluate.s"
	@echo "... src/front_end/ast.o"
	@echo "... src/front_end/ast.i"
	@echo "... src/front_end/ast.s"
	@echo "... src/front_end/parser.o"
	@echo "... src/front_end/parser.i"
	@echo "... src/front_end/parser.s"
	@echo "... src/front_end/scanner.o"
	@echo "... src/front_end/scanner.i"
	@echo "... src/front_end/scanner.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/middle_end/construct_ir_module.o"
	@echo "... src/middle_end/construct_ir_module.i"
	@echo "... src/middle_end/construct_ir_module.s"
	@echo "... src/middle_end/generate_ir.o"
	@echo "... src/middle_end/generate_ir.i"
	@echo "... src/middle_end/generate_ir.s"
	@echo "... src/middle_end/ir.o"
	@echo "... src/middle_end/ir.i"
	@echo "... src/middle_end/ir.s"
	@echo "... src/middle_end/ir_struct.o"
	@echo "... src/middle_end/ir_struct.i"
	@echo "... src/middle_end/ir_struct.s"
	@echo "... src/middle_end/ssa.o"
	@echo "... src/middle_end/ssa.i"
	@echo "... src/middle_end/ssa.s"
	@echo "... src/middle_end/ssa_struct.o"
	@echo "... src/middle_end/ssa_struct.i"
	@echo "... src/middle_end/ssa_struct.s"
	@echo "... src/optimizer/allocate_register.o"
	@echo "... src/optimizer/allocate_register.i"
	@echo "... src/optimizer/allocate_register.s"
	@echo "... src/optimizer/arm_liveness_analysis.o"
	@echo "... src/optimizer/arm_liveness_analysis.i"
	@echo "... src/optimizer/arm_liveness_analysis.s"
	@echo "... src/optimizer/arm_offset_fixup.o"
	@echo "... src/optimizer/arm_offset_fixup.i"
	@echo "... src/optimizer/arm_offset_fixup.s"
	@echo "... src/optimizer/cond_br_to_insts.o"
	@echo "... src/optimizer/cond_br_to_insts.i"
	@echo "... src/optimizer/cond_br_to_insts.s"
	@echo "... src/optimizer/constant_propagation.o"
	@echo "... src/optimizer/constant_propagation.i"
	@echo "... src/optimizer/constant_propagation.s"
	@echo "... src/optimizer/convert_ssa.o"
	@echo "... src/optimizer/convert_ssa.i"
	@echo "... src/optimizer/convert_ssa.s"
	@echo "... src/optimizer/dead_code_eliminate.o"
	@echo "... src/optimizer/dead_code_eliminate.i"
	@echo "... src/optimizer/dead_code_eliminate.s"
	@echo "... src/optimizer/dead_function_eliminate.o"
	@echo "... src/optimizer/dead_function_eliminate.i"
	@echo "... src/optimizer/dead_function_eliminate.s"
	@echo "... src/optimizer/dominant.o"
	@echo "... src/optimizer/dominant.i"
	@echo "... src/optimizer/dominant.s"
	@echo "... src/optimizer/generate_arm_from_ssa.o"
	@echo "... src/optimizer/generate_arm_from_ssa.i"
	@echo "... src/optimizer/generate_arm_from_ssa.s"
	@echo "... src/optimizer/global_value_numbering.o"
	@echo "... src/optimizer/global_value_numbering.i"
	@echo "... src/optimizer/global_value_numbering.s"
	@echo "... src/optimizer/instruction_combining.o"
	@echo "... src/optimizer/instruction_combining.i"
	@echo "... src/optimizer/instruction_combining.s"
	@echo "... src/optimizer/ir_liveness_analysis.o"
	@echo "... src/optimizer/ir_liveness_analysis.i"
	@echo "... src/optimizer/ir_liveness_analysis.s"
	@echo "... src/optimizer/loop_invariant_extrapolation.o"
	@echo "... src/optimizer/loop_invariant_extrapolation.i"
	@echo "... src/optimizer/loop_invariant_extrapolation.s"
	@echo "... src/optimizer/loop_unroll.o"
	@echo "... src/optimizer/loop_unroll.i"
	@echo "... src/optimizer/loop_unroll.s"
	@echo "... src/optimizer/reach_define.o"
	@echo "... src/optimizer/reach_define.i"
	@echo "... src/optimizer/reach_define.s"
	@echo "... src/optimizer/simplify_armcode.o"
	@echo "... src/optimizer/simplify_armcode.i"
	@echo "... src/optimizer/simplify_armcode.s"
	@echo "... src/optimizer/simplify_cfg.o"
	@echo "... src/optimizer/simplify_cfg.i"
	@echo "... src/optimizer/simplify_cfg.s"
	@echo "... src/optimizer/ssa_simple_optimize.o"
	@echo "... src/optimizer/ssa_simple_optimize.i"
	@echo "... src/optimizer/ssa_simple_optimize.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

