/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"

#include <cstdio>
#include <cstring>

// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);


#line 89 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "MinicBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_ID = 4,                       /* T_ID  */
  YYSYMBOL_T_FUNC = 5,                     /* T_FUNC  */
  YYSYMBOL_T_RETURN = 6,                   /* T_RETURN  */
  YYSYMBOL_T_IF = 7,                       /* T_IF  */
  YYSYMBOL_T_ELSE = 8,                     /* T_ELSE  */
  YYSYMBOL_T_WHILE = 9,                    /* T_WHILE  */
  YYSYMBOL_T_CONST = 10,                   /* T_CONST  */
  YYSYMBOL_T_INT = 11,                     /* T_INT  */
  YYSYMBOL_T_VOID = 12,                    /* T_VOID  */
  YYSYMBOL_T_BREAK = 13,                   /* T_BREAK  */
  YYSYMBOL_T_CONTINUE = 14,                /* T_CONTINUE  */
  YYSYMBOL_T_ADD = 15,                     /* T_ADD  */
  YYSYMBOL_T_SUB = 16,                     /* T_SUB  */
  YYSYMBOL_T_NOT = 17,                     /* T_NOT  */
  YYSYMBOL_T_MUL = 18,                     /* T_MUL  */
  YYSYMBOL_T_DIV = 19,                     /* T_DIV  */
  YYSYMBOL_T_MOD = 20,                     /* T_MOD  */
  YYSYMBOL_T_GTH = 21,                     /* T_GTH  */
  YYSYMBOL_T_LTH = 22,                     /* T_LTH  */
  YYSYMBOL_T_AND = 23,                     /* T_AND  */
  YYSYMBOL_T_OR = 24,                      /* T_OR  */
  YYSYMBOL_25_ = 25,                       /* '('  */
  YYSYMBOL_26_ = 26,                       /* ')'  */
  YYSYMBOL_27_ = 27,                       /* ';'  */
  YYSYMBOL_28_ = 28,                       /* ','  */
  YYSYMBOL_29_ = 29,                       /* '['  */
  YYSYMBOL_30_ = 30,                       /* ']'  */
  YYSYMBOL_31_ = 31,                       /* '{'  */
  YYSYMBOL_32_ = 32,                       /* '}'  */
  YYSYMBOL_33_ = 33,                       /* '='  */
  YYSYMBOL_YYACCEPT = 34,                  /* $accept  */
  YYSYMBOL_CompileUnit = 35,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 36,                   /* FuncDef  */
  YYSYMBOL_FuncFParams = 37,               /* FuncFParams  */
  YYSYMBOL_FuncFParam = 38,                /* FuncFParam  */
  YYSYMBOL_FuncFParamArray = 39,           /* FuncFParamArray  */
  YYSYMBOL_Block = 40,                     /* Block  */
  YYSYMBOL_BlockItemList = 41,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 42,                 /* BlockItem  */
  YYSYMBOL_Statement = 43,                 /* Statement  */
  YYSYMBOL_Cond = 44,                      /* Cond  */
  YYSYMBOL_Expr = 45,                      /* Expr  */
  YYSYMBOL_AddExp = 46,                    /* AddExp  */
  YYSYMBOL_MulExp = 47,                    /* MulExp  */
  YYSYMBOL_RelExp = 48,                    /* RelExp  */
  YYSYMBOL_EqExp = 49,                     /* EqExp  */
  YYSYMBOL_LAndExp = 50,                   /* LAndExp  */
  YYSYMBOL_LOrExp = 51,                    /* LOrExp  */
  YYSYMBOL_UnaryExp = 52,                  /* UnaryExp  */
  YYSYMBOL_Array = 53,                     /* Array  */
  YYSYMBOL_ArrayInitVal = 54,              /* ArrayInitVal  */
  YYSYMBOL_ArrayInitValList = 55,          /* ArrayInitValList  */
  YYSYMBOL_ExpList = 56,                   /* ExpList  */
  YYSYMBOL_ConstArrayInitVal = 57,         /* ConstArrayInitVal  */
  YYSYMBOL_ConstArrayInitValList = 58,     /* ConstArrayInitValList  */
  YYSYMBOL_ConstExpList = 59,              /* ConstExpList  */
  YYSYMBOL_Decl = 60,                      /* Decl  */
  YYSYMBOL_ConstDecl = 61,                 /* ConstDecl  */
  YYSYMBOL_ConstDefList = 62,              /* ConstDefList  */
  YYSYMBOL_ConstDef = 63,                  /* ConstDef  */
  YYSYMBOL_ConstExp = 64,                  /* ConstExp  */
  YYSYMBOL_ConstInitVal = 65,              /* ConstInitVal  */
  YYSYMBOL_VarDecl = 66,                   /* VarDecl  */
  YYSYMBOL_VarDefList = 67,                /* VarDefList  */
  YYSYMBOL_VarDef = 68,                    /* VarDef  */
  YYSYMBOL_InitVal = 69,                   /* InitVal  */
  YYSYMBOL_Btype = 70,                     /* Btype  */
  YYSYMBOL_PrimaryExp = 71,                /* PrimaryExp  */
  YYSYMBOL_LVal = 72,                      /* LVal  */
  YYSYMBOL_FuncRParams = 73                /* FuncRParams  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  12
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   291

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  34
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  40
/* YYNRULES -- Number of rules.  */
#define YYNRULES  107
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  204

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   279


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
      25,    26,     2,     2,    28,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,    27,
       2,    33,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,    29,     2,    30,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    31,     2,    32,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,    70,    70,    74,    77,    81,    87,    91,    95,    99,
     103,   107,   111,   115,   122,   125,   131,   136,   141,   150,
     159,   171,   175,   182,   187,   196,   199,   205,   212,   226,
     229,   233,   239,   242,   245,   248,   253,   259,   263,   269,
     275,   281,   287,   291,   295,   299,   304,   308,   312,   316,
     320,   325,   329,   333,   336,   339,   344,   348,   352,   355,
     358,   363,   367,   372,   375,   379,   383,   387,   391,   398,
     404,   410,   414,   420,   423,   429,   432,   439,   443,   449,
     452,   458,   461,   467,   470,   476,   479,   482,   488,   495,
     500,   505,   510,   515,   518,   523,   531,   538,   543,   550,
     558,   563,   567,   573,   580,   587,   593,   596
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT", "T_ID",
  "T_FUNC", "T_RETURN", "T_IF", "T_ELSE", "T_WHILE", "T_CONST", "T_INT",
  "T_VOID", "T_BREAK", "T_CONTINUE", "T_ADD", "T_SUB", "T_NOT", "T_MUL",
  "T_DIV", "T_MOD", "T_GTH", "T_LTH", "T_AND", "T_OR", "'('", "')'", "';'",
  "','", "'['", "']'", "'{'", "'}'", "'='", "$accept", "CompileUnit",
  "FuncDef", "FuncFParams", "FuncFParam", "FuncFParamArray", "Block",
  "BlockItemList", "BlockItem", "Statement", "Cond", "Expr", "AddExp",
  "MulExp", "RelExp", "EqExp", "LAndExp", "LOrExp", "UnaryExp", "Array",
  "ArrayInitVal", "ArrayInitValList", "ExpList", "ConstArrayInitVal",
  "ConstArrayInitValList", "ConstExpList", "Decl", "ConstDecl",
  "ConstDefList", "ConstDef", "ConstExp", "ConstInitVal", "VarDecl",
  "VarDefList", "VarDef", "InitVal", "Btype", "PrimaryExp", "LVal",
  "FuncRParams", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-138)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-39)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
      91,    17,  -138,    18,   142,  -138,  -138,  -138,  -138,    37,
      42,    50,  -138,  -138,  -138,     5,    59,   167,  -138,    66,
      67,   205,  -138,    31,    40,   107,   107,   107,    62,  -138,
      58,   107,    78,  -138,    42,    98,   159,  -138,    81,   112,
     188,  -138,   130,   107,   107,   107,   107,    52,   206,  -138,
      89,    97,  -138,  -138,  -138,    52,  -138,   106,    56,  -138,
     145,  -138,  -138,  -138,   214,  -138,  -138,  -138,   166,  -138,
     133,    17,   120,   172,  -138,  -138,   157,   243,  -138,  -138,
    -138,   115,   107,   107,   107,   107,   107,  -138,  -138,  -138,
    -138,   158,   161,  -138,   164,   176,  -138,   237,   146,   195,
     216,   224,  -138,  -138,   196,  -138,  -138,   230,  -138,    58,
     209,  -138,  -138,  -138,   219,   107,  -138,  -138,  -138,  -138,
     222,  -138,   206,   206,  -138,  -138,  -138,    62,  -138,   107,
    -138,    78,  -138,   107,  -138,  -138,   234,   262,   262,  -138,
    -138,  -138,  -138,  -138,   107,  -138,   233,   240,  -138,   107,
    -138,  -138,  -138,  -138,  -138,   262,   262,   241,    52,   136,
       3,   248,   249,   246,   247,  -138,  -138,  -138,     3,   248,
    -138,    54,     7,    94,   131,    28,    61,   242,   250,   253,
     256,   131,  -138,  -138,  -138,   273,   107,    52,   107,    52,
     107,   107,   262,   262,  -138,   131,    52,    52,   136,   136,
       3,   248,   248,  -138
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,     0,   100,     0,     0,     2,     4,    84,    83,     0,
       0,     0,     1,     3,     5,    96,    98,     0,    93,     0,
       0,     0,    86,     0,     0,     0,     0,     0,     0,    92,
       0,     0,     0,    85,     0,     0,     0,    14,     0,     0,
       0,   102,   104,     0,     0,     0,     0,    90,    41,    45,
     105,     0,    63,   103,    99,    38,    95,     0,     0,    97,
      96,    94,    91,    88,     0,    89,    87,    10,     0,     6,
       0,     0,    16,    17,    12,     8,     0,     0,    66,    67,
      68,     0,     0,     0,     0,     0,     0,    69,    70,    75,
      73,     0,     0,    79,     0,     0,    81,     0,     0,     0,
       0,     0,    21,    29,     0,    23,    25,     0,    26,     0,
     103,    11,     7,    15,     0,     0,    13,     9,    64,   106,
       0,   101,    39,    40,    42,    43,    44,     0,    72,     0,
      71,     0,    78,     0,    77,    36,     0,     0,     0,    33,
      34,    22,    24,    28,     0,    18,     0,     0,    65,     0,
      74,    76,    80,    82,    35,     0,     0,     0,    46,    51,
      56,    61,    37,     0,     0,    19,    20,   107,    55,    60,
      45,    46,    56,     0,     0,     0,     0,     0,     0,     0,
       0,     0,    27,    54,    59,    30,     0,    47,     0,    48,
       0,     0,     0,     0,    32,     0,    49,    50,    53,    52,
      56,    58,    62,    31
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -138,  -138,   278,   260,   217,  -138,   -18,  -138,   181,   -90,
     148,   -23,   -25,   155,    65,  -129,  -137,  -138,   -36,    -5,
     -45,  -138,  -138,   -48,  -138,  -138,   215,  -138,  -138,   255,
     -17,  -138,  -138,  -138,   261,  -138,    11,  -138,   -67,  -138
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_uint8 yydefgoto[] =
{
       0,     4,     5,    36,    37,    73,   103,   104,   105,   106,
     157,   107,    55,    48,   159,   160,   161,   162,    49,    50,
      59,    91,    92,    65,    94,    95,   108,     7,    21,    22,
      51,    63,     8,    17,    18,    56,    38,    52,    53,   120
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_int16 yytable[] =
{
      47,   110,    47,    54,    16,    20,    47,    78,    79,    80,
      57,     9,    10,    90,    62,     9,    93,    69,   169,   173,
     177,    75,    11,    81,   177,    16,   168,   172,     2,    20,
      24,    41,    42,   183,    25,    89,   178,   110,    26,    47,
     178,    15,     2,    43,    44,    45,    19,    96,   124,   125,
     126,     2,   112,    46,   119,   201,   202,    35,   117,    41,
      42,   186,    60,   200,    41,    42,    39,    82,    83,    82,
      83,    43,    44,    45,   136,    23,    43,    44,    45,   109,
     -38,    46,   150,   152,   185,    72,    46,    58,    27,    47,
      47,   194,    28,    58,   188,    25,    27,   146,   147,    31,
      32,     1,     2,     3,    16,   203,   151,   110,    47,    64,
      41,    42,   158,   158,   110,   109,   153,   179,    27,   170,
     184,   164,    43,    44,    45,    67,   167,    87,   110,    68,
     158,   171,    46,    81,    41,    42,    88,    97,    98,    74,
      99,   121,    12,    68,   100,   101,    43,    44,    45,   114,
     187,   189,     1,     2,     3,    77,    46,   175,   176,    25,
     111,   196,    68,   197,    68,   158,   158,   158,   158,    41,
      42,   137,    97,    98,    25,    99,     1,     2,    26,   100,
     101,    43,    44,    45,   116,    70,   127,    71,    68,   129,
     128,    46,   131,   130,    29,    30,   132,    68,   102,    41,
      42,   115,    97,    98,   133,    99,     1,     2,   134,   100,
     101,    43,    44,    45,    76,     6,    71,    41,    42,    14,
     138,    46,    41,    42,    84,    85,    86,    68,   141,    43,
      44,    45,    33,    34,    43,    44,    45,   122,   123,    46,
      41,    42,   144,   139,    46,    64,    41,    42,   148,   145,
     149,   140,    43,    44,    45,   198,   199,   143,    43,    44,
      45,   154,    46,   165,   135,    41,    42,   174,    46,   118,
     166,   179,   181,   180,   182,   190,   192,    43,    44,   155,
     193,   195,    13,   191,    40,   142,   163,   156,   113,    66,
       0,    61
};

static const yytype_int16 yycheck[] =
{
      25,    68,    27,    26,     9,    10,    31,    43,    44,    45,
      27,     0,     1,    58,    31,     4,    64,    35,   155,   156,
      17,    39,     4,    46,    17,    30,   155,   156,    11,    34,
      25,     3,     4,    26,    29,    58,    33,   104,    33,    64,
      33,     4,    11,    15,    16,    17,     4,    64,    84,    85,
      86,    11,    70,    25,    77,   192,   193,    26,    76,     3,
       4,    33,     4,   192,     3,     4,    26,    15,    16,    15,
      16,    15,    16,    17,    97,    25,    15,    16,    17,    68,
      26,    25,   127,   131,   174,     4,    25,    31,    29,   114,
     115,   181,    33,    31,    33,    29,    29,   114,   115,    33,
      33,    10,    11,    12,   109,   195,   129,   174,   133,    31,
       3,     4,   137,   138,   181,   104,   133,    23,    29,   155,
      26,   144,    15,    16,    17,    27,   149,    30,   195,    31,
     155,   156,    25,   156,     3,     4,    30,     6,     7,    27,
       9,    26,     0,    31,    13,    14,    15,    16,    17,    29,
     175,   176,    10,    11,    12,    25,    25,    21,    22,    29,
      27,   186,    31,   188,    31,   190,   191,   192,   193,     3,
       4,    25,     6,     7,    29,     9,    10,    11,    33,    13,
      14,    15,    16,    17,    27,    26,    28,    28,    31,    28,
      32,    25,    28,    32,    27,    28,    32,    31,    32,     3,
       4,    29,     6,     7,    28,     9,    10,    11,    32,    13,
      14,    15,    16,    17,    26,     0,    28,     3,     4,     4,
      25,    25,     3,     4,    18,    19,    20,    31,    32,    15,
      16,    17,    27,    28,    15,    16,    17,    82,    83,    25,
       3,     4,    33,    27,    25,    31,     3,     4,    26,    30,
      28,    27,    15,    16,    17,   190,   191,    27,    15,    16,
      17,    27,    25,    30,    27,     3,     4,    26,    25,    26,
      30,    23,    26,    24,    27,    33,    23,    15,    16,    17,
      24,     8,     4,    33,    24,   104,   138,    25,    71,    34,
      -1,    30
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,    10,    11,    12,    35,    36,    60,    61,    66,    70,
      70,     4,     0,    36,    60,     4,    53,    67,    68,     4,
      53,    62,    63,    25,    25,    29,    33,    29,    33,    27,
      28,    33,    33,    27,    28,    26,    37,    38,    70,    26,
      37,     3,     4,    15,    16,    17,    25,    46,    47,    52,
      53,    64,    71,    72,    45,    46,    69,    64,    31,    54,
       4,    68,    64,    65,    31,    57,    63,    27,    31,    40,
      26,    28,     4,    39,    27,    40,    26,    25,    52,    52,
      52,    45,    15,    16,    18,    19,    20,    30,    30,    45,
      54,    55,    56,    57,    58,    59,    64,     6,     7,     9,
      13,    14,    32,    40,    41,    42,    43,    45,    60,    70,
      72,    27,    40,    38,    29,    29,    27,    40,    26,    45,
      73,    26,    47,    47,    52,    52,    52,    28,    32,    28,
      32,    28,    32,    28,    32,    27,    45,    25,    25,    27,
      27,    32,    42,    27,    33,    30,    64,    64,    26,    28,
      54,    45,    57,    64,    27,    17,    25,    44,    46,    48,
      49,    50,    51,    44,    45,    30,    30,    45,    49,    50,
      52,    46,    49,    50,    26,    21,    22,    17,    33,    23,
      24,    26,    27,    26,    26,    43,    33,    46,    33,    46,
      33,    33,    23,    24,    43,     8,    46,    46,    48,    48,
      49,    50,    50,    43
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    34,    35,    35,    35,    35,    36,    36,    36,    36,
      36,    36,    36,    36,    37,    37,    38,    38,    39,    39,
      39,    40,    40,    41,    41,    42,    42,    43,    43,    43,
      43,    43,    43,    43,    43,    43,    43,    44,    45,    46,
      46,    46,    47,    47,    47,    47,    48,    48,    48,    48,
      48,    49,    49,    49,    49,    49,    50,    50,    50,    50,
      50,    51,    51,    52,    52,    52,    52,    52,    52,    53,
      53,    54,    54,    55,    55,    56,    56,    57,    57,    58,
      58,    59,    59,    60,    60,    61,    62,    62,    63,    63,
      64,    65,    66,    67,    67,    68,    68,    68,    68,    69,
      70,    71,    71,    71,    72,    72,    73,    73
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     2,     1,     2,     5,     6,     5,     6,
       5,     6,     5,     6,     1,     3,     2,     2,     3,     4,
       4,     2,     3,     1,     2,     1,     1,     4,     2,     1,
       5,     7,     5,     2,     2,     3,     2,     1,     1,     3,
       3,     1,     3,     3,     3,     1,     1,     3,     3,     4,
       4,     1,     4,     4,     3,     2,     1,     4,     4,     3,
       2,     1,     4,     1,     3,     4,     2,     2,     2,     4,
       4,     3,     3,     1,     3,     1,     3,     3,     3,     1,
       3,     1,     3,     1,     1,     4,     1,     3,     3,     3,
       1,     1,     3,     1,     3,     3,     1,     3,     1,     1,
       1,     3,     1,     1,     1,     1,     1,     3
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 70 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                      {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        ast_root = (yyval.node);
    }
#line 1305 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 3: /* CompileUnit: CompileUnit FuncDef  */
#line 74 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                          {
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1313 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 4: /* CompileUnit: Decl  */
#line 77 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
           {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        ast_root = (yyval.node);
    }
#line 1322 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit Decl  */
#line 81 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                       {
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1330 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 6: /* FuncDef: T_VOID T_ID '(' ')' Block  */
#line 87 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                     {
		/* 0代表void */
        (yyval.node) = create_func_def(0, (yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
    }
#line 1339 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 7: /* FuncDef: T_VOID T_ID '(' FuncFParams ')' Block  */
#line 91 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                            {
        /* 0代表void */
		(yyval.node) = create_func_def(0, (yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
    }
#line 1348 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 8: /* FuncDef: Btype T_ID '(' ')' Block  */
#line 95 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                    {
        /* 1代表int */
		(yyval.node) = create_func_def(1, (yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
    }
#line 1357 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 9: /* FuncDef: Btype T_ID '(' FuncFParams ')' Block  */
#line 99 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                           {
        /* 1代表int */
		(yyval.node) = create_func_def(1, (yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
    }
#line 1366 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 10: /* FuncDef: T_VOID T_ID '(' ')' ';'  */
#line 103 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                   {
		/* 0代表void */
        (yyval.node) = create_func_def(0, (yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, nullptr);
    }
#line 1375 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 11: /* FuncDef: T_VOID T_ID '(' FuncFParams ')' ';'  */
#line 107 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                          {
        /* 0代表void */
		(yyval.node) = create_func_def(0, (yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[-2].node));
    }
#line 1384 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 12: /* FuncDef: Btype T_ID '(' ')' ';'  */
#line 111 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                  {
        /* 1代表int */
		(yyval.node) = create_func_def(1, (yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id,  nullptr);
    }
#line 1393 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 13: /* FuncDef: Btype T_ID '(' FuncFParams ')' ';'  */
#line 115 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                         {
        /* 1代表int */
		(yyval.node) = create_func_def(1, (yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[-2].node));
    }
#line 1402 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 14: /* FuncFParams: FuncFParam  */
#line 122 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS, (yyvsp[0].node));
    }
#line 1410 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 15: /* FuncFParams: FuncFParams ',' FuncFParam  */
#line 125 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                 {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1418 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 16: /* FuncFParam: Btype T_ID  */
#line 131 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                         {
		ast_node * new_node = create_func_formal_param((yyvsp[0].var_id).lineno, (yyvsp[0].var_id).id);
        (yyval.node) = new_ast_node(ast_operator_type::AST_PARAM, (yyvsp[-1].node), new_node, nullptr);
    }
#line 1427 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 17: /* FuncFParam: Btype FuncFParamArray  */
#line 136 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                               {
		(yyval.node) = new_ast_node(ast_operator_type::AST_PARAM, (yyvsp[-1].node), (yyvsp[0].node), nullptr);
	}
#line 1435 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 18: /* FuncFParamArray: T_ID '[' ']'  */
#line 141 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                              {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});
		free((yyvsp[-2].var_id).id);

		char para[2]="*";
		ast_node * para_node = new_ast_leaf_node(var_id_attr{para, (yyvsp[-2].var_id).lineno});
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY,id_node, para_node, nullptr);
	}
#line 1448 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 19: /* FuncFParamArray: T_ID '[' ConstExp ']'  */
#line 150 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                             {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});

		free((yyvsp[-3].var_id).id);

		char para[2]="*";
		ast_node * para_node = new_ast_leaf_node(var_id_attr{para, (yyvsp[-3].var_id).lineno});
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY,id_node, para_node, nullptr);
	}
#line 1462 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 20: /* FuncFParamArray: FuncFParamArray '[' ConstExp ']'  */
#line 159 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                                {
		(yyval.node) = insert_ast_node((yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 1470 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 21: /* Block: '{' '}'  */
#line 171 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                {
        // 语句块没有语句
        (yyval.node) = nullptr;
    }
#line 1479 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 22: /* Block: '{' BlockItemList '}'  */
#line 175 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                            {
        // 语句块含有语句
        (yyval.node) = (yyvsp[-1].node);
    }
#line 1488 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 23: /* BlockItemList: BlockItem  */
#line 182 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                          {
        // 第一个左侧的孩子节点归约成Block父节点，后续语句可不断作为孩子追加到block中
        // 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node), nullptr);
    }
#line 1498 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 24: /* BlockItemList: BlockItemList BlockItem  */
#line 187 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                               {
        // 采用左递归的文法产生式，可以使得Block节点在上个产生式创建，后续递归追加孩子节点
        // 请注意，不要采用右递归，左递归翻遍孩子的追加
        // BlockItem($2)作为Block($1)的孩子 
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1509 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 25: /* BlockItem: Statement  */
#line 196 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                       {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1517 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 26: /* BlockItem: Decl  */
#line 199 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
              {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1525 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 27: /* Statement: LVal '=' Expr ';'  */
#line 205 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                              {
        // 归约到Statement时要执行的语义动作程序
        // 赋值语句，不显示值

        // 创建一个AST_OP_ASSIGN类型的中间节点，孩子为Id和Expr($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-3].node), (yyvsp[-1].node), nullptr);
    }
#line 1537 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 28: /* Statement: Expr ';'  */
#line 212 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                   {
        // Expr归约到Statement时要执行的语义动作程序
        // 表达式语句，不显示表达式的值

        // 创建一个AST_OP_EXPR类型的中间节点，孩子为Expr($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_EXPR, (yyvsp[-1].node), nullptr);
    }
#line 1549 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 29: /* Statement: Block  */
#line 226 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
               {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1557 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 30: /* Statement: T_IF '(' Cond ')' Statement  */
#line 229 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                    {
		// to do something
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1566 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 31: /* Statement: T_IF '(' Cond ')' Statement T_ELSE Statement  */
#line 233 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                                      {
		// 变量节点
		// ast_node * new_node = new_ast_node(ast_operator_type::AST_ELSE, $7, nullptr);
		ast_node * new_node = new_ast_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node), nullptr);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF, (yyvsp[-4].node), (yyvsp[-2].node), new_node, nullptr);
	}
#line 1577 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 32: /* Statement: T_WHILE '(' Cond ')' Statement  */
#line 239 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_WHILE, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1585 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 33: /* Statement: T_BREAK ';'  */
#line 242 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                     {
		(yyval.node) = new_ast_node(ast_operator_type::AST_BREAK, nullptr);
	}
#line 1593 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 34: /* Statement: T_CONTINUE ';'  */
#line 245 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_CONTINUE, nullptr);
    }
#line 1601 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 35: /* Statement: T_RETURN Expr ';'  */
#line 248 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                        {
        // 返回语句
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_RETURN_STATEMENT, (yyvsp[-1].node), nullptr);
    }
#line 1610 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 36: /* Statement: T_RETURN ';'  */
#line 253 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                     {
        // 返回语句 没有子节点代表不return
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_RETURN_STATEMENT, nullptr);
    }
#line 1619 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 37: /* Cond: LOrExp  */
#line 259 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
              {
		(yyval.node) = new_ast_node(ast_operator_type::AST_COND, (yyvsp[0].node), nullptr);
}
#line 1627 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 38: /* Expr: AddExp  */
#line 263 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
              {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1635 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 39: /* AddExp: AddExp T_ADD MulExp  */
#line 269 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                             {
        /* Expr = Expr + MulExp */

        // 创建一个AST_OP_ADD类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ADD, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1646 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 40: /* AddExp: AddExp T_SUB MulExp  */
#line 275 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                          {
        /* Expr = Expr + MulExp */

        // 创建一个AST_OP_ADD类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_SUB, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1657 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 41: /* AddExp: MulExp  */
#line 281 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1665 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 42: /* MulExp: MulExp T_MUL UnaryExp  */
#line 287 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                               {
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_MUL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1673 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 43: /* MulExp: MulExp T_DIV UnaryExp  */
#line 291 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                               {
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_DIV, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1681 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 44: /* MulExp: MulExp T_MOD UnaryExp  */
#line 295 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                               {
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_MOD, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1689 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 45: /* MulExp: UnaryExp  */
#line 299 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                  {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1697 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 46: /* RelExp: AddExp  */
#line 304 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1705 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 47: /* RelExp: RelExp T_GTH AddExp  */
#line 308 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                             {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_GTH, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1713 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 48: /* RelExp: RelExp T_LTH AddExp  */
#line 312 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                             {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_STH, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1721 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 49: /* RelExp: RelExp T_GTH '=' AddExp  */
#line 316 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                 {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_GOE, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1729 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 50: /* RelExp: RelExp T_LTH '=' AddExp  */
#line 320 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                 {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_SOE, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1737 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 51: /* EqExp: RelExp  */
#line 325 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
               {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1745 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 52: /* EqExp: EqExp '=' '=' RelExp  */
#line 329 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                              {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_EE, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1753 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 53: /* EqExp: EqExp T_NOT '=' RelExp  */
#line 333 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NE, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1761 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 54: /* EqExp: '(' EqExp ')'  */
#line 336 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                    {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1769 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 55: /* EqExp: T_NOT EqExp  */
#line 339 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                     {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NOT, (yyvsp[0].node), nullptr);
	}
#line 1777 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 56: /* LAndExp: EqExp  */
#line 344 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1785 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 57: /* LAndExp: LAndExp T_AND T_AND EqExp  */
#line 348 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                   {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ANDAND, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1793 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 58: /* LAndExp: LAndExp T_AND T_AND LAndExp  */
#line 352 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                     {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ANDAND, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1801 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 59: /* LAndExp: '(' LAndExp ')'  */
#line 355 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                      {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1809 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 60: /* LAndExp: T_NOT LAndExp  */
#line 358 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                       {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NOT, (yyvsp[0].node), nullptr);
	}
#line 1817 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 61: /* LOrExp: LAndExp  */
#line 363 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                 {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1825 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 62: /* LOrExp: LOrExp T_OR T_OR LAndExp  */
#line 367 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                  {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_OROR, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1833 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 63: /* UnaryExp: PrimaryExp  */
#line 372 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                      {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1841 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 64: /* UnaryExp: T_ID '(' ')'  */
#line 375 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                   {
        // 用户自定义的不含实参的函数调用
        (yyval.node) = create_func_call((yyvsp[-2].var_id).lineno, (yyvsp[-2].var_id).id, nullptr);
    }
#line 1850 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 65: /* UnaryExp: T_ID '(' FuncRParams ')'  */
#line 379 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                               {
        // 用户自定义的含有实参的参数调用
        (yyval.node) = create_func_call((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[-1].node));
    }
#line 1859 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 66: /* UnaryExp: T_ADD UnaryExp  */
#line 383 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                         {
		// 一元表达式
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ADD, (yyvsp[0].node), nullptr);
	}
#line 1868 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 67: /* UnaryExp: T_SUB UnaryExp  */
#line 387 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                         {
		// 一元表达式
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_SUB, (yyvsp[0].node), nullptr);
	}
#line 1877 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 68: /* UnaryExp: T_NOT UnaryExp  */
#line 391 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                         {
		// 一元表达式
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_NOT, (yyvsp[0].node), nullptr);
	}
#line 1886 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 69: /* Array: T_ID '[' ConstExp ']'  */
#line 398 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                            {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});

		free((yyvsp[-3].var_id).id);
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY,id_node, (yyvsp[-1].node), nullptr);
	}
#line 1897 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 70: /* Array: Array '[' ConstExp ']'  */
#line 404 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                        {
		(yyval.node) = insert_ast_node((yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 1905 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 71: /* ArrayInitVal: '{' ExpList '}'  */
#line 410 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                             {
		// 变量节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY_INIT_VAL, (yyvsp[-1].node), nullptr);
	}
#line 1914 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 72: /* ArrayInitVal: '{' ArrayInitValList '}'  */
#line 414 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY_INIT_VAL, (yyvsp[-1].node), nullptr);
	}
#line 1922 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 73: /* ArrayInitValList: ArrayInitVal  */
#line 420 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                {
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY_INIT_VAL_LIST, (yyvsp[0].node), nullptr);
	}
#line 1930 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 74: /* ArrayInitValList: ArrayInitValList ',' ArrayInitVal  */
#line 423 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                           {
		(yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1938 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 75: /* ExpList: Expr  */
#line 429 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
              {
        (yyval.node) = new_ast_node(ast_operator_type::AST_EXP_LIST, (yyvsp[0].node), nullptr);
    }
#line 1946 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 76: /* ExpList: ExpList ',' Expr  */
#line 432 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                      {
		(yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1954 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 77: /* ConstArrayInitVal: '{' ConstExpList '}'  */
#line 439 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                       {
		// 变量节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_CONST_ARRAY_INIT_VAL, (yyvsp[-1].node), nullptr);
	}
#line 1963 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 78: /* ConstArrayInitVal: '{' ConstArrayInitValList '}'  */
#line 443 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_CONST_ARRAY_INIT_VAL, (yyvsp[-1].node), nullptr);
	}
#line 1971 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 79: /* ConstArrayInitValList: ConstArrayInitVal  */
#line 449 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                          {
		(yyval.node) = new_ast_node(ast_operator_type::AST_CONST_ARRAY_INIT_VAL_LIST, (yyvsp[0].node), nullptr);
	}
#line 1979 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 80: /* ConstArrayInitValList: ConstArrayInitValList ',' ConstArrayInitVal  */
#line 452 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                                     {
		(yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1987 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 81: /* ConstExpList: ConstExp  */
#line 458 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                       {
        (yyval.node) = new_ast_node(ast_operator_type::AST_CONST_EXP_LIST, (yyvsp[0].node), nullptr);
    }
#line 1995 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 82: /* ConstExpList: ConstExpList ',' ConstExp  */
#line 461 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                               {
		(yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2003 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 83: /* Decl: VarDecl  */
#line 467 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                  {
	    (yyval.node) = (yyvsp[0].node);
    }
#line 2011 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 84: /* Decl: ConstDecl  */
#line 470 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
               {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2019 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 85: /* ConstDecl: T_CONST Btype ConstDefList ';'  */
#line 476 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                          {
		(yyval.node) = new_ast_node(ast_operator_type::AST_VAR_CONST_DECL, (yyvsp[-2].node), (yyvsp[-1].node), nullptr);
	}
#line 2027 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 86: /* ConstDefList: ConstDef  */
#line 479 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                       {
		(yyval.node) = new_ast_node(ast_operator_type::AST_VAR_CONST_DEF, (yyvsp[0].node), nullptr);
	}
#line 2035 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 87: /* ConstDefList: ConstDefList ',' ConstDef  */
#line 482 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                   {
		(yyval.node) = insert_ast_node((yyvsp[-2].node) , (yyvsp[0].node));
	}
#line 2043 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 88: /* ConstDef: T_ID '=' ConstInitVal  */
#line 488 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                  {
		// 变量节点
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

		free((yyvsp[-2].var_id).id);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node), nullptr);
	}
#line 2055 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 89: /* ConstDef: Array '=' ConstArrayInitVal  */
#line 495 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                     {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 2063 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 90: /* ConstExp: AddExp  */
#line 500 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                 {
	    (yyval.node) = (yyvsp[0].node);
    }
#line 2071 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 91: /* ConstInitVal: ConstExp  */
#line 505 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                        {
        (yyval.node) = (yyvsp[0].node);
    }
#line 2079 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 92: /* VarDecl: Btype VarDefList ';'  */
#line 510 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                              {
		(yyval.node) = new_ast_node(ast_operator_type::AST_VAR_VAR_DECL, (yyvsp[-2].node), (yyvsp[-1].node), nullptr);
	}
#line 2087 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 93: /* VarDefList: VarDef  */
#line 515 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                  {
		(yyval.node) = new_ast_node(ast_operator_type::AST_VAR_VAR_DEF, (yyvsp[0].node), nullptr);
	}
#line 2095 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 94: /* VarDefList: VarDefList ',' VarDef  */
#line 518 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                               {
		(yyval.node) = insert_ast_node((yyvsp[-2].node) , (yyvsp[0].node));
	}
#line 2103 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 95: /* VarDef: T_ID '=' InitVal  */
#line 523 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                           {
		// 变量节点
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

		free((yyvsp[-2].var_id).id);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node), nullptr);
	}
#line 2115 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 96: /* VarDef: T_ID  */
#line 531 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
             {
		// 变量节点
        ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

        free((yyvsp[0].var_id).id);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, nullptr);
	}
#line 2127 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 97: /* VarDef: Array '=' ArrayInitVal  */
#line 538 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                                 {
		// 变量节点

		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 2137 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 98: /* VarDef: Array  */
#line 543 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                {
		// 变量节点

		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[0].node), nullptr);
	}
#line 2147 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 99: /* InitVal: Expr  */
#line 550 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
              {
		/* 可以是多种式子 */
		(yyval.node) = (yyvsp[0].node);
	}
#line 2156 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 100: /* Btype: T_INT  */
#line 558 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
             {
		(yyval.node) = new_ast_node(ast_operator_type::AST_TYPE_INT, nullptr);
	}
#line 2164 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 101: /* PrimaryExp: '(' Expr ')'  */
#line 563 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                           {
        /* PrimaryExp = Expr */
        (yyval.node) = (yyvsp[-1].node);
    }
#line 2173 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 102: /* PrimaryExp: T_DIGIT  */
#line 567 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
              {
        // 无符号整数识别

        // 终结符作为抽象语法树的叶子节点进行创建
        (yyval.node) = new_ast_leaf_node(digit_int_attr{(yyvsp[0].integer_num).val, (yyvsp[0].integer_num).lineno});
    }
#line 2184 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 103: /* PrimaryExp: LVal  */
#line 573 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
            {
        // 左值
        (yyval.node) = (yyvsp[0].node);
    }
#line 2193 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 104: /* LVal: T_ID  */
#line 580 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
            {
        // 终结符作为抽象语法树的叶子节点进行创建
        (yyval.node) = new_ast_leaf_node(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
    }
#line 2205 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 105: /* LVal: Array  */
#line 587 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
               {
		// 左值
        (yyval.node) = (yyvsp[0].node);
	}
#line 2214 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 106: /* FuncRParams: Expr  */
#line 593 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                   {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
    }
#line 2222 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 107: /* FuncRParams: FuncRParams ',' Expr  */
#line 596 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"
                           {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2230 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;


#line 2234 "/home/code/SimpleCompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 600 "/home/code/SimpleCompiler/frontend/AST/flexbison/Minic.y"


// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}
