/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"

#include <cstdio>
#include <cstring>

// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);


#line 89 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "MinicBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_ID = 4,                       /* T_ID  */
  YYSYMBOL_T_FUNC = 5,                     /* T_FUNC  */
  YYSYMBOL_T_RETURN = 6,                   /* T_RETURN  */
  YYSYMBOL_T_IF = 7,                       /* T_IF  */
  YYSYMBOL_T_ELSE = 8,                     /* T_ELSE  */
  YYSYMBOL_T_WHILE = 9,                    /* T_WHILE  */
  YYSYMBOL_T_CONST = 10,                   /* T_CONST  */
  YYSYMBOL_T_INT = 11,                     /* T_INT  */
  YYSYMBOL_T_VOID = 12,                    /* T_VOID  */
  YYSYMBOL_T_BREAK = 13,                   /* T_BREAK  */
  YYSYMBOL_T_CONTINUE = 14,                /* T_CONTINUE  */
  YYSYMBOL_T_ADD = 15,                     /* T_ADD  */
  YYSYMBOL_T_SUB = 16,                     /* T_SUB  */
  YYSYMBOL_T_NOT = 17,                     /* T_NOT  */
  YYSYMBOL_T_MUL = 18,                     /* T_MUL  */
  YYSYMBOL_T_DIV = 19,                     /* T_DIV  */
  YYSYMBOL_T_MOD = 20,                     /* T_MOD  */
  YYSYMBOL_T_GTH = 21,                     /* T_GTH  */
  YYSYMBOL_T_LTH = 22,                     /* T_LTH  */
  YYSYMBOL_T_AND = 23,                     /* T_AND  */
  YYSYMBOL_T_OR = 24,                      /* T_OR  */
  YYSYMBOL_25_ = 25,                       /* '('  */
  YYSYMBOL_26_ = 26,                       /* ')'  */
  YYSYMBOL_27_ = 27,                       /* ','  */
  YYSYMBOL_28_ = 28,                       /* '['  */
  YYSYMBOL_29_ = 29,                       /* ']'  */
  YYSYMBOL_30_ = 30,                       /* '{'  */
  YYSYMBOL_31_ = 31,                       /* '}'  */
  YYSYMBOL_32_ = 32,                       /* '='  */
  YYSYMBOL_33_ = 33,                       /* ';'  */
  YYSYMBOL_YYACCEPT = 34,                  /* $accept  */
  YYSYMBOL_CompileUnit = 35,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 36,                   /* FuncDef  */
  YYSYMBOL_FuncFParams = 37,               /* FuncFParams  */
  YYSYMBOL_FuncFParam = 38,                /* FuncFParam  */
  YYSYMBOL_FuncFParamArray = 39,           /* FuncFParamArray  */
  YYSYMBOL_Block = 40,                     /* Block  */
  YYSYMBOL_BlockItemList = 41,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 42,                 /* BlockItem  */
  YYSYMBOL_Statement = 43,                 /* Statement  */
  YYSYMBOL_Cond = 44,                      /* Cond  */
  YYSYMBOL_Expr = 45,                      /* Expr  */
  YYSYMBOL_AddExp = 46,                    /* AddExp  */
  YYSYMBOL_MulExp = 47,                    /* MulExp  */
  YYSYMBOL_RelExp = 48,                    /* RelExp  */
  YYSYMBOL_EqExp = 49,                     /* EqExp  */
  YYSYMBOL_LAndExp = 50,                   /* LAndExp  */
  YYSYMBOL_LOrExp = 51,                    /* LOrExp  */
  YYSYMBOL_UnaryExp = 52,                  /* UnaryExp  */
  YYSYMBOL_Array = 53,                     /* Array  */
  YYSYMBOL_ArrayInitVal = 54,              /* ArrayInitVal  */
  YYSYMBOL_ArrayInitValList = 55,          /* ArrayInitValList  */
  YYSYMBOL_ExpList = 56,                   /* ExpList  */
  YYSYMBOL_ConstArrayInitVal = 57,         /* ConstArrayInitVal  */
  YYSYMBOL_ConstArrayInitValList = 58,     /* ConstArrayInitValList  */
  YYSYMBOL_ConstExpList = 59,              /* ConstExpList  */
  YYSYMBOL_Decl = 60,                      /* Decl  */
  YYSYMBOL_ConstDecl = 61,                 /* ConstDecl  */
  YYSYMBOL_ConstDefList = 62,              /* ConstDefList  */
  YYSYMBOL_ConstDef = 63,                  /* ConstDef  */
  YYSYMBOL_ConstExp = 64,                  /* ConstExp  */
  YYSYMBOL_ConstInitVal = 65,              /* ConstInitVal  */
  YYSYMBOL_VarDecl = 66,                   /* VarDecl  */
  YYSYMBOL_VarDefList = 67,                /* VarDefList  */
  YYSYMBOL_VarDef = 68,                    /* VarDef  */
  YYSYMBOL_InitVal = 69,                   /* InitVal  */
  YYSYMBOL_Btype = 70,                     /* Btype  */
  YYSYMBOL_PrimaryExp = 71,                /* PrimaryExp  */
  YYSYMBOL_LVal = 72,                      /* LVal  */
  YYSYMBOL_FuncRParams = 73                /* FuncRParams  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  12
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   265

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  34
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  40
/* YYNRULES -- Number of rules.  */
#define YYNRULES  98
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  189

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   279


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
      25,    26,     2,     2,    27,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,    33,
       2,    32,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,    28,     2,    29,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    30,     2,    31,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,    70,    70,    74,    77,    81,    87,    91,    95,    99,
     106,   109,   115,   120,   125,   134,   143,   155,   159,   166,
     171,   180,   183,   189,   196,   210,   213,   217,   223,   226,
     229,   232,   237,   243,   247,   253,   259,   265,   271,   275,
     279,   283,   288,   292,   296,   300,   304,   309,   313,   317,
     322,   326,   331,   335,   340,   343,   347,   351,   355,   359,
     366,   372,   378,   382,   388,   391,   397,   400,   407,   411,
     417,   420,   426,   429,   435,   438,   444,   447,   450,   456,
     463,   468,   473,   478,   483,   486,   491,   499,   506,   511,
     518,   526,   531,   535,   541,   548,   555,   561,   564
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT", "T_ID",
  "T_FUNC", "T_RETURN", "T_IF", "T_ELSE", "T_WHILE", "T_CONST", "T_INT",
  "T_VOID", "T_BREAK", "T_CONTINUE", "T_ADD", "T_SUB", "T_NOT", "T_MUL",
  "T_DIV", "T_MOD", "T_GTH", "T_LTH", "T_AND", "T_OR", "'('", "')'", "','",
  "'['", "']'", "'{'", "'}'", "'='", "';'", "$accept", "CompileUnit",
  "FuncDef", "FuncFParams", "FuncFParam", "FuncFParamArray", "Block",
  "BlockItemList", "BlockItem", "Statement", "Cond", "Expr", "AddExp",
  "MulExp", "RelExp", "EqExp", "LAndExp", "LOrExp", "UnaryExp", "Array",
  "ArrayInitVal", "ArrayInitValList", "ExpList", "ConstArrayInitVal",
  "ConstArrayInitValList", "ConstExpList", "Decl", "ConstDecl",
  "ConstDefList", "ConstDef", "ConstExp", "ConstInitVal", "VarDecl",
  "VarDefList", "VarDef", "InitVal", "Btype", "PrimaryExp", "LVal",
  "FuncRParams", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-150)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
     160,    19,  -150,    17,    68,  -150,  -150,  -150,  -150,    39,
      41,    40,  -150,  -150,  -150,    -3,    16,    13,  -150,    29,
      32,    20,  -150,     7,     8,   240,   240,   240,    44,    84,
    -150,   240,    81,    41,  -150,    86,    74,  -150,   137,    86,
      97,  -150,    48,   240,   240,   240,   240,   105,   155,  -150,
     118,   119,  -150,  -150,  -150,   105,  -150,   121,   115,  -150,
      53,  -150,  -150,  -150,   217,  -150,  -150,   152,  -150,    86,
      19,   129,   132,  -150,    86,   235,  -150,  -150,  -150,   138,
     240,   240,   240,   240,   240,  -150,  -150,  -150,  -150,    35,
      64,  -150,    66,    79,  -150,    34,   151,   153,   146,   147,
    -150,  -150,   181,  -150,  -150,   148,  -150,    84,   154,  -150,
    -150,   220,   240,  -150,  -150,  -150,   102,  -150,   155,   155,
    -150,  -150,  -150,    44,  -150,   240,  -150,    81,  -150,   240,
    -150,  -150,   156,   240,   240,  -150,  -150,  -150,  -150,  -150,
     240,  -150,   164,   170,  -150,   240,  -150,  -150,  -150,  -150,
    -150,   174,   105,   112,     9,   178,   179,   176,   180,  -150,
    -150,  -150,   201,    67,   110,   177,   187,   199,   203,   201,
    -150,   221,   240,   105,   240,   105,   240,   240,   240,   240,
    -150,   201,   105,   105,   112,   112,     9,   178,  -150
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,     0,    91,     0,     0,     2,     4,    75,    74,     0,
       0,     0,     1,     3,     5,    87,    89,     0,    84,     0,
       0,     0,    77,     0,     0,     0,     0,     0,     0,     0,
      83,     0,     0,     0,    76,     0,     0,    10,     0,     0,
       0,    93,    95,     0,     0,     0,     0,    81,    37,    41,
      96,     0,    54,    94,    90,    34,    86,     0,     0,    88,
      87,    85,    82,    79,     0,    80,    78,     0,     6,     0,
       0,    12,    13,     8,     0,     0,    57,    58,    59,     0,
       0,     0,     0,     0,     0,    60,    61,    66,    64,     0,
       0,    70,     0,     0,    72,     0,     0,     0,     0,     0,
      17,    25,     0,    19,    21,     0,    22,     0,    94,     7,
      11,     0,     0,     9,    55,    97,     0,    92,    35,    36,
      38,    39,    40,     0,    63,     0,    62,     0,    69,     0,
      68,    32,     0,     0,     0,    29,    30,    18,    20,    24,
       0,    14,     0,     0,    56,     0,    65,    67,    71,    73,
      31,     0,    42,    47,    50,    52,    33,     0,     0,    15,
      16,    98,     0,     0,     0,     0,     0,     0,     0,     0,
      23,    26,     0,    43,     0,    44,     0,     0,     0,     0,
      28,     0,    45,    46,    49,    48,    51,    53,    27
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -150,  -150,   224,   206,   171,  -150,   -11,  -150,   123,  -149,
     106,   -23,   -25,    56,   -33,    70,    75,  -150,   -28,    -2,
     -54,  -150,  -150,   -52,  -150,  -150,    94,  -150,  -150,   213,
     -22,  -150,  -150,  -150,   229,  -150,    10,  -150,   -66,  -150
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_uint8 yydefgoto[] =
{
       0,     4,     5,    36,    37,    72,   101,   102,   103,   104,
     151,   105,    55,    48,   153,   154,   155,   156,    49,    50,
      59,    89,    90,    65,    92,    93,   106,     7,    21,    22,
      51,    63,     8,    17,    18,    56,    38,    52,    53,   116
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
      47,   108,    47,    54,    88,    57,    47,    16,    20,    62,
       9,    10,    91,   171,     9,    76,    77,    78,     2,     2,
     180,    11,    24,    79,    68,    25,   165,    16,    73,    26,
       2,    20,   188,    35,    39,    87,   108,    41,    42,    47,
      29,   166,    94,    15,    27,    19,    30,    33,    28,    43,
      44,    45,   115,    34,   120,   121,   122,    25,   109,    46,
      27,    31,   123,   113,    32,    23,   124,   131,    12,   146,
      41,    42,   132,    75,    58,   148,    25,   107,     1,     2,
       3,    25,    43,    44,    45,    26,    47,    47,    60,   142,
     143,   125,    46,   127,     6,   126,   108,   128,    14,   172,
      69,    70,   147,   108,    47,    16,   129,   149,   152,   152,
     130,    64,   107,    41,    42,   108,    67,   158,    41,    42,
      80,    81,   161,    74,    70,    43,    44,    45,   144,   145,
      43,    44,    45,   163,   164,    46,   118,   119,   173,   175,
      46,    71,   174,   184,   185,    58,    27,   182,    85,   183,
      86,   152,   152,   152,   152,    41,    42,   111,    95,    96,
     112,    97,     1,     2,   117,    98,    99,    43,    44,    45,
       1,     2,     3,    82,    83,    84,   133,    46,   134,   135,
     136,   139,    67,   100,    41,    42,   140,    95,    96,   150,
      97,     1,     2,   159,    98,    99,    43,    44,    45,   160,
     162,   167,   169,   168,    41,    42,    46,    95,    96,   176,
      97,    67,   137,   170,    98,    99,    43,    44,    45,   177,
      41,    42,   178,    41,    42,   138,    46,   179,    13,   181,
      40,    67,    43,    44,    45,    43,    44,    45,    41,    42,
     157,   110,    46,    41,    42,    46,    66,    64,   186,   141,
      43,    44,    45,     0,   187,    43,    44,    45,    61,     0,
      46,   114,     0,     0,     0,    46
};

static const yytype_int16 yycheck[] =
{
      25,    67,    27,    26,    58,    27,    31,     9,    10,    31,
       0,     1,    64,   162,     4,    43,    44,    45,    11,    11,
     169,     4,    25,    46,    35,    28,    17,    29,    39,    32,
      11,    33,   181,    26,    26,    58,   102,     3,     4,    64,
      27,    32,    64,     4,    28,     4,    33,    27,    32,    15,
      16,    17,    75,    33,    82,    83,    84,    28,    69,    25,
      28,    32,    27,    74,    32,    25,    31,    33,     0,   123,
       3,     4,    95,    25,    30,   127,    28,    67,    10,    11,
      12,    28,    15,    16,    17,    32,   111,   112,     4,   111,
     112,    27,    25,    27,     0,    31,   162,    31,     4,    32,
      26,    27,   125,   169,   129,   107,    27,   129,   133,   134,
      31,    30,   102,     3,     4,   181,    30,   140,     3,     4,
      15,    16,   145,    26,    27,    15,    16,    17,    26,    27,
      15,    16,    17,    21,    22,    25,    80,    81,   163,   164,
      25,     4,    32,   176,   177,    30,    28,   172,    29,   174,
      29,   176,   177,   178,   179,     3,     4,    28,     6,     7,
      28,     9,    10,    11,    26,    13,    14,    15,    16,    17,
      10,    11,    12,    18,    19,    20,    25,    25,    25,    33,
      33,    33,    30,    31,     3,     4,    32,     6,     7,    33,
       9,    10,    11,    29,    13,    14,    15,    16,    17,    29,
      26,    23,    26,    24,     3,     4,    25,     6,     7,    32,
       9,    30,    31,    33,    13,    14,    15,    16,    17,    32,
       3,     4,    23,     3,     4,   102,    25,    24,     4,     8,
      24,    30,    15,    16,    17,    15,    16,    17,     3,     4,
     134,    70,    25,     3,     4,    25,    33,    30,   178,    29,
      15,    16,    17,    -1,   179,    15,    16,    17,    29,    -1,
      25,    26,    -1,    -1,    -1,    25
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,    10,    11,    12,    35,    36,    60,    61,    66,    70,
      70,     4,     0,    36,    60,     4,    53,    67,    68,     4,
      53,    62,    63,    25,    25,    28,    32,    28,    32,    27,
      33,    32,    32,    27,    33,    26,    37,    38,    70,    26,
      37,     3,     4,    15,    16,    17,    25,    46,    47,    52,
      53,    64,    71,    72,    45,    46,    69,    64,    30,    54,
       4,    68,    64,    65,    30,    57,    63,    30,    40,    26,
      27,     4,    39,    40,    26,    25,    52,    52,    52,    45,
      15,    16,    18,    19,    20,    29,    29,    45,    54,    55,
      56,    57,    58,    59,    64,     6,     7,     9,    13,    14,
      31,    40,    41,    42,    43,    45,    60,    70,    72,    40,
      38,    28,    28,    40,    26,    45,    73,    26,    47,    47,
      52,    52,    52,    27,    31,    27,    31,    27,    31,    27,
      31,    33,    45,    25,    25,    33,    33,    31,    42,    33,
      32,    29,    64,    64,    26,    27,    54,    45,    57,    64,
      33,    44,    46,    48,    49,    50,    51,    44,    45,    29,
      29,    45,    26,    21,    22,    17,    32,    23,    24,    26,
      33,    43,    32,    46,    32,    46,    32,    32,    23,    24,
      43,     8,    46,    46,    48,    48,    49,    50,    43
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    34,    35,    35,    35,    35,    36,    36,    36,    36,
      37,    37,    38,    38,    39,    39,    39,    40,    40,    41,
      41,    42,    42,    43,    43,    43,    43,    43,    43,    43,
      43,    43,    43,    44,    45,    46,    46,    46,    47,    47,
      47,    47,    48,    48,    48,    48,    48,    49,    49,    49,
      50,    50,    51,    51,    52,    52,    52,    52,    52,    52,
      53,    53,    54,    54,    55,    55,    56,    56,    57,    57,
      58,    58,    59,    59,    60,    60,    61,    62,    62,    63,
      63,    64,    65,    66,    67,    67,    68,    68,    68,    68,
      69,    70,    71,    71,    71,    72,    72,    73,    73
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     2,     1,     2,     5,     6,     5,     6,
       1,     3,     2,     2,     3,     4,     4,     2,     3,     1,
       2,     1,     1,     4,     2,     1,     5,     7,     5,     2,
       2,     3,     2,     1,     1,     3,     3,     1,     3,     3,
       3,     1,     1,     3,     3,     4,     4,     1,     4,     4,
       1,     4,     1,     4,     1,     3,     4,     2,     2,     2,
       4,     4,     3,     3,     1,     3,     1,     3,     3,     3,
       1,     3,     1,     3,     1,     1,     4,     1,     3,     3,
       3,     1,     1,     3,     1,     3,     3,     1,     3,     1,
       1,     1,     3,     1,     1,     1,     1,     1,     3
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 70 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                      {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        ast_root = (yyval.node);
    }
#line 1290 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 3: /* CompileUnit: CompileUnit FuncDef  */
#line 74 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                          {
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1298 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 4: /* CompileUnit: Decl  */
#line 77 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
           {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
        ast_root = (yyval.node);
    }
#line 1307 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit Decl  */
#line 81 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                       {
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1315 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 6: /* FuncDef: T_VOID T_ID '(' ')' Block  */
#line 87 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                     {
		/* 0代表void */
        (yyval.node) = create_func_def(0, (yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
    }
#line 1324 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 7: /* FuncDef: T_VOID T_ID '(' FuncFParams ')' Block  */
#line 91 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                            {
        /* 0代表void */
		(yyval.node) = create_func_def(0, (yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
    }
#line 1333 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 8: /* FuncDef: Btype T_ID '(' ')' Block  */
#line 95 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                    {
        /* 1代表int */
		(yyval.node) = create_func_def(1, (yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[0].node), nullptr);
    }
#line 1342 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 9: /* FuncDef: Btype T_ID '(' FuncFParams ')' Block  */
#line 99 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                           {
        /* 1代表int */
		(yyval.node) = create_func_def(1, (yyvsp[-4].var_id).lineno, (yyvsp[-4].var_id).id, (yyvsp[0].node), (yyvsp[-2].node));
    }
#line 1351 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 10: /* FuncFParams: FuncFParam  */
#line 106 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS, (yyvsp[0].node));
    }
#line 1359 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 11: /* FuncFParams: FuncFParams ',' FuncFParam  */
#line 109 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                 {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1367 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 12: /* FuncFParam: Btype T_ID  */
#line 115 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                         {
		ast_node * new_node = create_func_formal_param((yyvsp[0].var_id).lineno, (yyvsp[0].var_id).id);
        (yyval.node) = new_ast_node(ast_operator_type::AST_PARAM, (yyvsp[-1].node), new_node, nullptr);
    }
#line 1376 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 13: /* FuncFParam: Btype FuncFParamArray  */
#line 120 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                               {
		(yyval.node) = new_ast_node(ast_operator_type::AST_PARAM, (yyvsp[-1].node), (yyvsp[0].node), nullptr);
	}
#line 1384 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 14: /* FuncFParamArray: T_ID '[' ']'  */
#line 125 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                              {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});
		free((yyvsp[-2].var_id).id);

		char para[2]="*";
		ast_node * para_node = new_ast_leaf_node(var_id_attr{para, (yyvsp[-2].var_id).lineno});
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY,id_node, para_node, nullptr);
	}
#line 1397 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 15: /* FuncFParamArray: T_ID '[' ConstExp ']'  */
#line 134 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                             {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});

		free((yyvsp[-3].var_id).id);

		char para[2]="*";
		ast_node * para_node = new_ast_leaf_node(var_id_attr{para, (yyvsp[-3].var_id).lineno});
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY,id_node, para_node, nullptr);
	}
#line 1411 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 16: /* FuncFParamArray: FuncFParamArray '[' ConstExp ']'  */
#line 143 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                                {
		(yyval.node) = insert_ast_node((yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 1419 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 17: /* Block: '{' '}'  */
#line 155 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                {
        // 语句块没有语句
        (yyval.node) = nullptr;
    }
#line 1428 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 18: /* Block: '{' BlockItemList '}'  */
#line 159 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                            {
        // 语句块含有语句
        (yyval.node) = (yyvsp[-1].node);
    }
#line 1437 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 19: /* BlockItemList: BlockItem  */
#line 166 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                          {
        // 第一个左侧的孩子节点归约成Block父节点，后续语句可不断作为孩子追加到block中
        // 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node), nullptr);
    }
#line 1447 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 20: /* BlockItemList: BlockItemList BlockItem  */
#line 171 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                               {
        // 采用左递归的文法产生式，可以使得Block节点在上个产生式创建，后续递归追加孩子节点
        // 请注意，不要采用右递归，左递归翻遍孩子的追加
        // BlockItem($2)作为Block($1)的孩子 
        (yyval.node) = insert_ast_node((yyvsp[-1].node), (yyvsp[0].node));
    }
#line 1458 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 21: /* BlockItem: Statement  */
#line 180 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                       {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1466 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 22: /* BlockItem: Decl  */
#line 183 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
              {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1474 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 23: /* Statement: LVal '=' Expr ';'  */
#line 189 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                              {
        // 归约到Statement时要执行的语义动作程序
        // 赋值语句，不显示值

        // 创建一个AST_OP_ASSIGN类型的中间节点，孩子为Id和Expr($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-3].node), (yyvsp[-1].node), nullptr);
    }
#line 1486 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 24: /* Statement: Expr ';'  */
#line 196 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                   {
        // Expr归约到Statement时要执行的语义动作程序
        // 表达式语句，不显示表达式的值

        // 创建一个AST_OP_EXPR类型的中间节点，孩子为Expr($1)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_EXPR, (yyvsp[-1].node), nullptr);
    }
#line 1498 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 25: /* Statement: Block  */
#line 210 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
               {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1506 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 26: /* Statement: T_IF '(' Cond ')' Statement  */
#line 213 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                    {
		// to do something
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1515 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 27: /* Statement: T_IF '(' Cond ')' Statement T_ELSE Statement  */
#line 217 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                                      {
		// 变量节点
		// ast_node * new_node = new_ast_node(ast_operator_type::AST_ELSE, $7, nullptr);
		ast_node * new_node = new_ast_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node), nullptr);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_IF, (yyvsp[-4].node), (yyvsp[-2].node), new_node, nullptr);
	}
#line 1526 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 28: /* Statement: T_WHILE '(' Cond ')' Statement  */
#line 223 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_WHILE, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1534 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 29: /* Statement: T_BREAK ';'  */
#line 226 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                     {
		(yyval.node) = new_ast_node(ast_operator_type::AST_BREAK, nullptr);
	}
#line 1542 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 30: /* Statement: T_CONTINUE ';'  */
#line 229 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_CONTINUE, nullptr);
    }
#line 1550 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 31: /* Statement: T_RETURN Expr ';'  */
#line 232 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                        {
        // 返回语句
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_RETURN_STATEMENT, (yyvsp[-1].node), nullptr);
    }
#line 1559 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 32: /* Statement: T_RETURN ';'  */
#line 237 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                     {
        // 返回语句 没有子节点代表不return
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_RETURN_STATEMENT, nullptr);
    }
#line 1568 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 33: /* Cond: LOrExp  */
#line 243 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
              {
		(yyval.node) = new_ast_node(ast_operator_type::AST_COND, (yyvsp[0].node), nullptr);
}
#line 1576 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 34: /* Expr: AddExp  */
#line 247 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
              {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1584 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 35: /* AddExp: AddExp T_ADD MulExp  */
#line 253 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                             {
        /* Expr = Expr + MulExp */

        // 创建一个AST_OP_ADD类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ADD, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1595 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 36: /* AddExp: AddExp T_SUB MulExp  */
#line 259 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                          {
        /* Expr = Expr + MulExp */

        // 创建一个AST_OP_ADD类型的中间节点，孩子为Expr($1)和Term($3)
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_SUB, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1606 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 37: /* AddExp: MulExp  */
#line 265 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1614 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 38: /* MulExp: MulExp T_MUL UnaryExp  */
#line 271 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                               {
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_MUL, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1622 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 39: /* MulExp: MulExp T_DIV UnaryExp  */
#line 275 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                               {
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_DIV, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1630 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 40: /* MulExp: MulExp T_MOD UnaryExp  */
#line 279 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                               {
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_MOD, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
    }
#line 1638 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 41: /* MulExp: UnaryExp  */
#line 283 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                  {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1646 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 42: /* RelExp: AddExp  */
#line 288 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1654 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 43: /* RelExp: RelExp T_GTH AddExp  */
#line 292 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                             {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_GTH, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1662 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 44: /* RelExp: RelExp T_LTH AddExp  */
#line 296 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                             {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_STH, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1670 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 45: /* RelExp: RelExp T_GTH '=' AddExp  */
#line 300 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                 {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_GOE, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1678 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 46: /* RelExp: RelExp T_LTH '=' AddExp  */
#line 304 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                 {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_SOE, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1686 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 47: /* EqExp: RelExp  */
#line 309 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
               {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1694 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 48: /* EqExp: EqExp '=' '=' RelExp  */
#line 313 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                              {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_EE, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1702 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 49: /* EqExp: EqExp T_NOT '=' RelExp  */
#line 317 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_NE, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1710 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 50: /* LAndExp: EqExp  */
#line 322 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1718 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 51: /* LAndExp: LAndExp T_AND T_AND EqExp  */
#line 326 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                   {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ANDAND, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1726 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 52: /* LOrExp: LAndExp  */
#line 331 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                 {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1734 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 53: /* LOrExp: LOrExp T_OR T_OR LAndExp  */
#line 335 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                  {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_OROR, (yyvsp[-3].node), (yyvsp[0].node), nullptr);
	}
#line 1742 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 54: /* UnaryExp: PrimaryExp  */
#line 340 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                      {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1750 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 55: /* UnaryExp: T_ID '(' ')'  */
#line 343 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                   {
        // 用户自定义的不含实参的函数调用
        (yyval.node) = create_func_call((yyvsp[-2].var_id).lineno, (yyvsp[-2].var_id).id, nullptr);
    }
#line 1759 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 56: /* UnaryExp: T_ID '(' FuncRParams ')'  */
#line 347 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                               {
        // 用户自定义的含有实参的参数调用
        (yyval.node) = create_func_call((yyvsp[-3].var_id).lineno, (yyvsp[-3].var_id).id, (yyvsp[-1].node));
    }
#line 1768 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 57: /* UnaryExp: T_ADD UnaryExp  */
#line 351 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                         {
		// 一元表达式
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_ADD, (yyvsp[0].node), nullptr);
	}
#line 1777 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 58: /* UnaryExp: T_SUB UnaryExp  */
#line 355 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                         {
		// 一元表达式
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_SUB, (yyvsp[0].node), nullptr);
	}
#line 1786 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 59: /* UnaryExp: T_NOT UnaryExp  */
#line 359 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                         {
		// 一元表达式
        (yyval.node) = new_ast_node(ast_operator_type::AST_OP_NOT, (yyvsp[0].node), nullptr);
	}
#line 1795 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 60: /* Array: T_ID '[' ConstExp ']'  */
#line 366 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                            {
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});

		free((yyvsp[-3].var_id).id);
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY,id_node, (yyvsp[-1].node), nullptr);
	}
#line 1806 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 61: /* Array: Array '[' ConstExp ']'  */
#line 372 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                        {
		(yyval.node) = insert_ast_node((yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 1814 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 62: /* ArrayInitVal: '{' ExpList '}'  */
#line 378 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                             {
		// 变量节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY_INIT_VAL, (yyvsp[-1].node), nullptr);
	}
#line 1823 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 63: /* ArrayInitVal: '{' ArrayInitValList '}'  */
#line 382 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY_INIT_VAL, (yyvsp[-1].node), nullptr);
	}
#line 1831 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 64: /* ArrayInitValList: ArrayInitVal  */
#line 388 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                {
		(yyval.node) = new_ast_node(ast_operator_type::AST_ARRAY_INIT_VAL_LIST, (yyvsp[0].node), nullptr);
	}
#line 1839 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 65: /* ArrayInitValList: ArrayInitValList ',' ArrayInitVal  */
#line 391 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                           {
		(yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1847 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 66: /* ExpList: Expr  */
#line 397 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
              {
        (yyval.node) = new_ast_node(ast_operator_type::AST_EXP_LIST, (yyvsp[0].node), nullptr);
    }
#line 1855 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 67: /* ExpList: ExpList ',' Expr  */
#line 400 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                      {
		(yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1863 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 68: /* ConstArrayInitVal: '{' ConstExpList '}'  */
#line 407 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                       {
		// 变量节点
		(yyval.node) = new_ast_node(ast_operator_type::AST_CONST_ARRAY_INIT_VAL, (yyvsp[-1].node), nullptr);
	}
#line 1872 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 69: /* ConstArrayInitVal: '{' ConstArrayInitValList '}'  */
#line 411 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                        {
		(yyval.node) = new_ast_node(ast_operator_type::AST_CONST_ARRAY_INIT_VAL, (yyvsp[-1].node), nullptr);
	}
#line 1880 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 70: /* ConstArrayInitValList: ConstArrayInitVal  */
#line 417 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                          {
		(yyval.node) = new_ast_node(ast_operator_type::AST_CONST_ARRAY_INIT_VAL_LIST, (yyvsp[0].node), nullptr);
	}
#line 1888 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 71: /* ConstArrayInitValList: ConstArrayInitValList ',' ConstArrayInitVal  */
#line 420 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                                     {
		(yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1896 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 72: /* ConstExpList: ConstExp  */
#line 426 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                       {
        (yyval.node) = new_ast_node(ast_operator_type::AST_CONST_EXP_LIST, (yyvsp[0].node), nullptr);
    }
#line 1904 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 73: /* ConstExpList: ConstExpList ',' ConstExp  */
#line 429 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                               {
		(yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1912 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 74: /* Decl: VarDecl  */
#line 435 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                  {
	    (yyval.node) = (yyvsp[0].node);
    }
#line 1920 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 75: /* Decl: ConstDecl  */
#line 438 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
               {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1928 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 76: /* ConstDecl: T_CONST Btype ConstDefList ';'  */
#line 444 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                          {
		(yyval.node) = new_ast_node(ast_operator_type::AST_VAR_CONST_DECL, (yyvsp[-2].node), (yyvsp[-1].node), nullptr);
	}
#line 1936 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 77: /* ConstDefList: ConstDef  */
#line 447 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                       {
		(yyval.node) = new_ast_node(ast_operator_type::AST_VAR_CONST_DEF, (yyvsp[0].node), nullptr);
	}
#line 1944 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 78: /* ConstDefList: ConstDefList ',' ConstDef  */
#line 450 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                   {
		(yyval.node) = insert_ast_node((yyvsp[-2].node) , (yyvsp[0].node));
	}
#line 1952 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 79: /* ConstDef: T_ID '=' ConstInitVal  */
#line 456 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                  {
		// 变量节点
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

		free((yyvsp[-2].var_id).id);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node), nullptr);
	}
#line 1964 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 80: /* ConstDef: Array '=' ConstArrayInitVal  */
#line 463 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                     {
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 1972 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 81: /* ConstExp: AddExp  */
#line 468 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                 {
	    (yyval.node) = (yyvsp[0].node);
    }
#line 1980 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 82: /* ConstInitVal: ConstExp  */
#line 473 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                        {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1988 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 83: /* VarDecl: Btype VarDefList ';'  */
#line 478 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                              {
		(yyval.node) = new_ast_node(ast_operator_type::AST_VAR_VAR_DECL, (yyvsp[-2].node), (yyvsp[-1].node), nullptr);
	}
#line 1996 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 84: /* VarDefList: VarDef  */
#line 483 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                  {
		(yyval.node) = new_ast_node(ast_operator_type::AST_VAR_VAR_DEF, (yyvsp[0].node), nullptr);
	}
#line 2004 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 85: /* VarDefList: VarDefList ',' VarDef  */
#line 486 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                               {
		(yyval.node) = insert_ast_node((yyvsp[-2].node) , (yyvsp[0].node));
	}
#line 2012 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 86: /* VarDef: T_ID '=' InitVal  */
#line 491 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                           {
		// 变量节点
		ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});

		free((yyvsp[-2].var_id).id);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node), nullptr);
	}
#line 2024 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 87: /* VarDef: T_ID  */
#line 499 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
             {
		// 变量节点
        ast_node * id_node = new_ast_leaf_node(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

        free((yyvsp[0].var_id).id);
		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, id_node, nullptr);
	}
#line 2036 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 88: /* VarDef: Array '=' ArrayInitVal  */
#line 506 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                                 {
		// 变量节点

		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-2].node), (yyvsp[0].node), nullptr);
	}
#line 2046 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 89: /* VarDef: Array  */
#line 511 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                {
		// 变量节点

		(yyval.node) = new_ast_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[0].node), nullptr);
	}
#line 2056 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 90: /* InitVal: Expr  */
#line 518 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
              {
		/* 可以是多种式子 */
		(yyval.node) = (yyvsp[0].node);
	}
#line 2065 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 91: /* Btype: T_INT  */
#line 526 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
             {
		(yyval.node) = new_ast_node(ast_operator_type::AST_TYPE_INT, nullptr);
	}
#line 2073 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 92: /* PrimaryExp: '(' Expr ')'  */
#line 531 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                           {
        /* PrimaryExp = Expr */
        (yyval.node) = (yyvsp[-1].node);
    }
#line 2082 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 93: /* PrimaryExp: T_DIGIT  */
#line 535 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
              {
        // 无符号整数识别

        // 终结符作为抽象语法树的叶子节点进行创建
        (yyval.node) = new_ast_leaf_node(digit_int_attr{(yyvsp[0].integer_num).val, (yyvsp[0].integer_num).lineno});
    }
#line 2093 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 94: /* PrimaryExp: LVal  */
#line 541 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
            {
        // 左值
        (yyval.node) = (yyvsp[0].node);
    }
#line 2102 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 95: /* LVal: T_ID  */
#line 548 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
            {
        // 终结符作为抽象语法树的叶子节点进行创建
        (yyval.node) = new_ast_leaf_node(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
    }
#line 2114 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 96: /* LVal: Array  */
#line 555 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
               {
		// 左值
        (yyval.node) = (yyvsp[0].node);
	}
#line 2123 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 97: /* FuncRParams: Expr  */
#line 561 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                   {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
    }
#line 2131 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;

  case 98: /* FuncRParams: FuncRParams ',' Expr  */
#line 564 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"
                           {
        (yyval.node) = insert_ast_node((yyvsp[-2].node), (yyvsp[0].node));
    }
#line 2139 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"
    break;


#line 2143 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/autogenerated/MinicBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 568 "/home/code/tmp/simplecompiler/frontend/AST/flexbison/Minic.y"


// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}
